//===========================================================================
//
// Name:			bulwark_c.c
// Function:		bulwark character profile
// Source:			WORR original Q3-style BotLib seed
// Tab Size:		4 (real tabs)
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME					"Bulwark"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.26
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/bulwark_w.c"
	CHARACTERISTIC_AIM_SKILL			0.32
	CHARACTERISTIC_AIM_ACCURACY			0.32
	CHARACTERISTIC_VIEW_FACTOR			0.43
	CHARACTERISTIC_VIEW_MAXCHANGE		105
	CHARACTERISTIC_REACTIONTIME			1.220

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.30
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.32
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.33
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.30
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.28
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.29
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.35
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.31
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.35
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.32
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.32
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.28

	CHARACTERISTIC_CHAT_FILE			"bots/bulwark_t.c"
	CHARACTERISTIC_CHAT_NAME			"bulwark"
	CHARACTERISTIC_CHAT_CPM				195
	CHARACTERISTIC_CHAT_INSULT			0.03
	CHARACTERISTIC_CHAT_MISC			0.29
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.16
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.16
	CHARACTERISTIC_CHAT_KILL			0.13
	CHARACTERISTIC_CHAT_DEATH			0.13
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.07
	CHARACTERISTIC_CHAT_HITTALKING		0.03
	CHARACTERISTIC_CHAT_HITNODEATH		0.16
	CHARACTERISTIC_CHAT_HITNOKILL		0.10
	CHARACTERISTIC_CHAT_RANDOM			0.16
	CHARACTERISTIC_CHAT_REPLY			0.23

	CHARACTERISTIC_CROUCHER				0.40
	CHARACTERISTIC_JUMPER				0.16
	CHARACTERISTIC_WEAPONJUMPING		0.07
	CHARACTERISTIC_GRAPPLE_USER			0.03
	CHARACTERISTIC_WALKER				0.47

	CHARACTERISTIC_ITEMWEIGHTS			"bots/bulwark_i.c"
	CHARACTERISTIC_AGGRESSION			0.24
	CHARACTERISTIC_SELFPRESERVATION		0.95
	CHARACTERISTIC_VENGEFULNESS			0.21
	CHARACTERISTIC_CAMPER				0.73
	CHARACTERISTIC_EASY_FRAGGER			0.09
	CHARACTERISTIC_ALERTNESS			0.41
	CHARACTERISTIC_FIRETHROTTLE			0.32

	WORR_SKIN							"male/pointman"
	WORR_TEAM							"blue"
	WORR_AIM_ERROR						7
	WORR_PREFERRED_WEAPON				"shotgun"
	WORR_CHAT_PERSONALITY				"steady"
	WORR_ROLE							"defender"
	WORR_MOVEMENT_STYLE					"anchor"
	WORR_REACTION_JITTER_MS				220
	WORR_AIM_TRACKING_NOISE				5.00
	WORR_AIM_LEAD_SCALE					0.70
	WORR_COMBAT_FOV						100
	WORR_TEAMPLAY_BIAS					0.72
	WORR_OBJECTIVE_BIAS					0.78
	WORR_FRIENDLY_FIRE_CARE				0.80
	WORR_ITEM_GREED						0.48
	WORR_ITEM_DENIAL					0.70
	WORR_POWERUP_TIMING					0.50
	WORR_RETREAT_HEALTH					65
} //end skill 1 bulwark

skill 2
{
	CHARACTERISTIC_NAME					"Bulwark"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.38
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/bulwark_w.c"
	CHARACTERISTIC_AIM_SKILL			0.46
	CHARACTERISTIC_AIM_ACCURACY			0.46
	CHARACTERISTIC_VIEW_FACTOR			0.51
	CHARACTERISTIC_VIEW_MAXCHANGE		129
	CHARACTERISTIC_REACTIONTIME			0.620

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.39
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.41
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.43
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.39
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.36
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.38
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.45
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.40
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.46
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.42
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.41
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.36

	CHARACTERISTIC_CHAT_FILE			"bots/bulwark_t.c"
	CHARACTERISTIC_CHAT_NAME			"bulwark"
	CHARACTERISTIC_CHAT_CPM				234
	CHARACTERISTIC_CHAT_INSULT			0.04
	CHARACTERISTIC_CHAT_MISC			0.38
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.21
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.21
	CHARACTERISTIC_CHAT_KILL			0.17
	CHARACTERISTIC_CHAT_DEATH			0.17
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.09
	CHARACTERISTIC_CHAT_HITTALKING		0.04
	CHARACTERISTIC_CHAT_HITNODEATH		0.21
	CHARACTERISTIC_CHAT_HITNOKILL		0.13
	CHARACTERISTIC_CHAT_RANDOM			0.21
	CHARACTERISTIC_CHAT_REPLY			0.30

	CHARACTERISTIC_CROUCHER				0.40
	CHARACTERISTIC_JUMPER				0.21
	CHARACTERISTIC_WEAPONJUMPING		0.09
	CHARACTERISTIC_GRAPPLE_USER			0.04
	CHARACTERISTIC_WALKER				0.39

	CHARACTERISTIC_ITEMWEIGHTS			"bots/bulwark_i.c"
	CHARACTERISTIC_AGGRESSION			0.35
	CHARACTERISTIC_SELFPRESERVATION		0.89
	CHARACTERISTIC_VENGEFULNESS			0.30
	CHARACTERISTIC_CAMPER				0.68
	CHARACTERISTIC_EASY_FRAGGER			0.13
	CHARACTERISTIC_ALERTNESS			0.59
	CHARACTERISTIC_FIRETHROTTLE			0.46

	WORR_SKIN							"male/pointman"
	WORR_TEAM							"blue"
	WORR_AIM_ERROR						5
	WORR_PREFERRED_WEAPON				"shotgun"
	WORR_CHAT_PERSONALITY				"steady"
	WORR_ROLE							"defender"
	WORR_MOVEMENT_STYLE					"anchor"
	WORR_REACTION_JITTER_MS				160
	WORR_AIM_TRACKING_NOISE				3.50
	WORR_AIM_LEAD_SCALE					0.82
	WORR_COMBAT_FOV						112
	WORR_TEAMPLAY_BIAS					0.82
	WORR_OBJECTIVE_BIAS					0.86
	WORR_FRIENDLY_FIRE_CARE				0.88
	WORR_ITEM_GREED						0.55
	WORR_ITEM_DENIAL					0.80
	WORR_POWERUP_TIMING					0.60
	WORR_RETREAT_HEALTH					58
} //end skill 2 bulwark

skill 3
{
	CHARACTERISTIC_NAME					"Bulwark"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.45
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/bulwark_w.c"
	CHARACTERISTIC_AIM_SKILL			0.55
	CHARACTERISTIC_AIM_ACCURACY			0.55
	CHARACTERISTIC_VIEW_FACTOR			0.55
	CHARACTERISTIC_VIEW_MAXCHANGE		150
	CHARACTERISTIC_REACTIONTIME			0.320

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.43
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.45
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.47
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.43
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.40
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.42
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.50
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.44
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.51
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.46
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.45
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.40

	CHARACTERISTIC_CHAT_FILE			"bots/bulwark_t.c"
	CHARACTERISTIC_CHAT_NAME			"bulwark"
	CHARACTERISTIC_CHAT_CPM				260
	CHARACTERISTIC_CHAT_INSULT			0.05
	CHARACTERISTIC_CHAT_MISC			0.45
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.25
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.25
	CHARACTERISTIC_CHAT_KILL			0.20
	CHARACTERISTIC_CHAT_DEATH			0.20
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.10
	CHARACTERISTIC_CHAT_HITTALKING		0.05
	CHARACTERISTIC_CHAT_HITNODEATH		0.25
	CHARACTERISTIC_CHAT_HITNOKILL		0.15
	CHARACTERISTIC_CHAT_RANDOM			0.25
	CHARACTERISTIC_CHAT_REPLY			0.35

	CHARACTERISTIC_CROUCHER				0.40
	CHARACTERISTIC_JUMPER				0.25
	CHARACTERISTIC_WEAPONJUMPING		0.10
	CHARACTERISTIC_GRAPPLE_USER			0.05
	CHARACTERISTIC_WALKER				0.35

	CHARACTERISTIC_ITEMWEIGHTS			"bots/bulwark_i.c"
	CHARACTERISTIC_AGGRESSION			0.42
	CHARACTERISTIC_SELFPRESERVATION		0.85
	CHARACTERISTIC_VENGEFULNESS			0.35
	CHARACTERISTIC_CAMPER				0.65
	CHARACTERISTIC_EASY_FRAGGER			0.15
	CHARACTERISTIC_ALERTNESS			0.70
	CHARACTERISTIC_FIRETHROTTLE			0.55

	WORR_SKIN							"male/pointman"
	WORR_TEAM							"blue"
	WORR_AIM_ERROR						4
	WORR_PREFERRED_WEAPON				"shotgun"
	WORR_CHAT_PERSONALITY				"steady"
	WORR_ROLE							"defender"
	WORR_MOVEMENT_STYLE					"anchor"
	WORR_REACTION_JITTER_MS				110
	WORR_AIM_TRACKING_NOISE				2.50
	WORR_AIM_LEAD_SCALE					0.92
	WORR_COMBAT_FOV						124
	WORR_TEAMPLAY_BIAS					0.90
	WORR_OBJECTIVE_BIAS					0.92
	WORR_FRIENDLY_FIRE_CARE				0.94
	WORR_ITEM_GREED						0.62
	WORR_ITEM_DENIAL					0.88
	WORR_POWERUP_TIMING					0.70
	WORR_RETREAT_HEALTH					52
} //end skill 3 bulwark

