//===========================================================================
//
// Name:			relay_c.c
// Function:		relay character profile
// Source:			WORR original Q3-style BotLib seed
// Tab Size:		4 (real tabs)
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME					"Relay"
	CHARACTERISTIC_GENDER				"female"
	CHARACTERISTIC_ATTACK_SKILL			0.34
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/relay_w.c"
	CHARACTERISTIC_AIM_SKILL			0.36
	CHARACTERISTIC_AIM_ACCURACY			0.35
	CHARACTERISTIC_VIEW_FACTOR			0.55
	CHARACTERISTIC_VIEW_MAXCHANGE		133
	CHARACTERISTIC_REACTIONTIME			1.160

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.33
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.34
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.36
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.33
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.30
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.32
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.38
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.34
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.40
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.36
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.36
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.31

	CHARACTERISTIC_CHAT_FILE			"bots/relay_t.c"
	CHARACTERISTIC_CHAT_NAME			"relay"
	CHARACTERISTIC_CHAT_CPM				255
	CHARACTERISTIC_CHAT_INSULT			0.07
	CHARACTERISTIC_CHAT_MISC			0.45
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.23
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.29
	CHARACTERISTIC_CHAT_KILL			0.16
	CHARACTERISTIC_CHAT_DEATH			0.20
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.13
	CHARACTERISTIC_CHAT_HITTALKING		0.07
	CHARACTERISTIC_CHAT_HITNODEATH		0.26
	CHARACTERISTIC_CHAT_HITNOKILL		0.23
	CHARACTERISTIC_CHAT_RANDOM			0.23
	CHARACTERISTIC_CHAT_REPLY			0.36

	CHARACTERISTIC_CROUCHER				0.20
	CHARACTERISTIC_JUMPER				0.36
	CHARACTERISTIC_WEAPONJUMPING		0.20
	CHARACTERISTIC_GRAPPLE_USER			0.16
	CHARACTERISTIC_WALKER				0.32

	CHARACTERISTIC_ITEMWEIGHTS			"bots/relay_i.c"
	CHARACTERISTIC_AGGRESSION			0.32
	CHARACTERISTIC_SELFPRESERVATION		0.75
	CHARACTERISTIC_VENGEFULNESS			0.27
	CHARACTERISTIC_CAMPER				0.28
	CHARACTERISTIC_EASY_FRAGGER			0.14
	CHARACTERISTIC_ALERTNESS			0.45
	CHARACTERISTIC_FIRETHROTTLE			0.23

	WORR_SKIN							"female/athena"
	WORR_TEAM							"free"
	WORR_AIM_ERROR						6
	WORR_PREFERRED_WEAPON				"hyperblaster"
	WORR_CHAT_PERSONALITY				"helpful"
	WORR_ROLE							"support"
	WORR_MOVEMENT_STYLE					"patrol"
	WORR_REACTION_JITTER_MS				200
	WORR_AIM_TRACKING_NOISE				4.60
	WORR_AIM_LEAD_SCALE					0.75
	WORR_COMBAT_FOV						115
	WORR_TEAMPLAY_BIAS					0.78
	WORR_OBJECTIVE_BIAS					0.62
	WORR_FRIENDLY_FIRE_CARE				0.82
	WORR_ITEM_GREED						0.55
	WORR_ITEM_DENIAL					0.45
	WORR_POWERUP_TIMING					0.58
	WORR_RETREAT_HEALTH					60
} //end skill 1 relay

skill 2
{
	CHARACTERISTIC_NAME					"Relay"
	CHARACTERISTIC_GENDER				"female"
	CHARACTERISTIC_ATTACK_SKILL			0.49
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/relay_w.c"
	CHARACTERISTIC_AIM_SKILL			0.52
	CHARACTERISTIC_AIM_ACCURACY			0.50
	CHARACTERISTIC_VIEW_FACTOR			0.64
	CHARACTERISTIC_VIEW_MAXCHANGE		163
	CHARACTERISTIC_REACTIONTIME			0.560

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.42
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.44
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.46
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.42
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.39
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.41
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.49
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.43
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.51
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.47
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.46
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.40

	CHARACTERISTIC_CHAT_FILE			"bots/relay_t.c"
	CHARACTERISTIC_CHAT_NAME			"relay"
	CHARACTERISTIC_CHAT_CPM				306
	CHARACTERISTIC_CHAT_INSULT			0.09
	CHARACTERISTIC_CHAT_MISC			0.59
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.30
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.38
	CHARACTERISTIC_CHAT_KILL			0.21
	CHARACTERISTIC_CHAT_DEATH			0.26
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.17
	CHARACTERISTIC_CHAT_HITTALKING		0.09
	CHARACTERISTIC_CHAT_HITNODEATH		0.34
	CHARACTERISTIC_CHAT_HITNOKILL		0.30
	CHARACTERISTIC_CHAT_RANDOM			0.30
	CHARACTERISTIC_CHAT_REPLY			0.47

	CHARACTERISTIC_CROUCHER				0.20
	CHARACTERISTIC_JUMPER				0.47
	CHARACTERISTIC_WEAPONJUMPING		0.26
	CHARACTERISTIC_GRAPPLE_USER			0.21
	CHARACTERISTIC_WALKER				0.24

	CHARACTERISTIC_ITEMWEIGHTS			"bots/relay_i.c"
	CHARACTERISTIC_AGGRESSION			0.46
	CHARACTERISTIC_SELFPRESERVATION		0.69
	CHARACTERISTIC_VENGEFULNESS			0.38
	CHARACTERISTIC_CAMPER				0.23
	CHARACTERISTIC_EASY_FRAGGER			0.21
	CHARACTERISTIC_ALERTNESS			0.66
	CHARACTERISTIC_FIRETHROTTLE			0.34

	WORR_SKIN							"female/athena"
	WORR_TEAM							"free"
	WORR_AIM_ERROR						4
	WORR_PREFERRED_WEAPON				"hyperblaster"
	WORR_CHAT_PERSONALITY				"helpful"
	WORR_ROLE							"support"
	WORR_MOVEMENT_STYLE					"patrol"
	WORR_REACTION_JITTER_MS				140
	WORR_AIM_TRACKING_NOISE				3.20
	WORR_AIM_LEAD_SCALE					0.88
	WORR_COMBAT_FOV						128
	WORR_TEAMPLAY_BIAS					0.88
	WORR_OBJECTIVE_BIAS					0.70
	WORR_FRIENDLY_FIRE_CARE				0.90
	WORR_ITEM_GREED						0.62
	WORR_ITEM_DENIAL					0.55
	WORR_POWERUP_TIMING					0.68
	WORR_RETREAT_HEALTH					52
} //end skill 2 relay

skill 3
{
	CHARACTERISTIC_NAME					"Relay"
	CHARACTERISTIC_GENDER				"female"
	CHARACTERISTIC_ATTACK_SKILL			0.58
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/relay_w.c"
	CHARACTERISTIC_AIM_SKILL			0.62
	CHARACTERISTIC_AIM_ACCURACY			0.60
	CHARACTERISTIC_VIEW_FACTOR			0.70
	CHARACTERISTIC_VIEW_MAXCHANGE		190
	CHARACTERISTIC_REACTIONTIME			0.260

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.47
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.49
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.52
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.47
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.43
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.46
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.54
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.48
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.57
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.52
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.51
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.45

	CHARACTERISTIC_CHAT_FILE			"bots/relay_t.c"
	CHARACTERISTIC_CHAT_NAME			"relay"
	CHARACTERISTIC_CHAT_CPM				340
	CHARACTERISTIC_CHAT_INSULT			0.10
	CHARACTERISTIC_CHAT_MISC			0.70
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.35
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.45
	CHARACTERISTIC_CHAT_KILL			0.25
	CHARACTERISTIC_CHAT_DEATH			0.30
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.20
	CHARACTERISTIC_CHAT_HITTALKING		0.10
	CHARACTERISTIC_CHAT_HITNODEATH		0.40
	CHARACTERISTIC_CHAT_HITNOKILL		0.35
	CHARACTERISTIC_CHAT_RANDOM			0.35
	CHARACTERISTIC_CHAT_REPLY			0.55

	CHARACTERISTIC_CROUCHER				0.20
	CHARACTERISTIC_JUMPER				0.55
	CHARACTERISTIC_WEAPONJUMPING		0.30
	CHARACTERISTIC_GRAPPLE_USER			0.25
	CHARACTERISTIC_WALKER				0.20

	CHARACTERISTIC_ITEMWEIGHTS			"bots/relay_i.c"
	CHARACTERISTIC_AGGRESSION			0.55
	CHARACTERISTIC_SELFPRESERVATION		0.65
	CHARACTERISTIC_VENGEFULNESS			0.45
	CHARACTERISTIC_CAMPER				0.20
	CHARACTERISTIC_EASY_FRAGGER			0.25
	CHARACTERISTIC_ALERTNESS			0.78
	CHARACTERISTIC_FIRETHROTTLE			0.40

	WORR_SKIN							"female/athena"
	WORR_TEAM							"free"
	WORR_AIM_ERROR						3
	WORR_PREFERRED_WEAPON				"hyperblaster"
	WORR_CHAT_PERSONALITY				"helpful"
	WORR_ROLE							"support"
	WORR_MOVEMENT_STYLE					"patrol"
	WORR_REACTION_JITTER_MS				95
	WORR_AIM_TRACKING_NOISE				2.20
	WORR_AIM_LEAD_SCALE					1.00
	WORR_COMBAT_FOV						140
	WORR_TEAMPLAY_BIAS					0.95
	WORR_OBJECTIVE_BIAS					0.78
	WORR_FRIENDLY_FIRE_CARE				0.96
	WORR_ITEM_GREED						0.68
	WORR_ITEM_DENIAL					0.65
	WORR_POWERUP_TIMING					0.78
	WORR_RETREAT_HEALTH					45
} //end skill 3 relay

