//===========================================================================
//
// Name:			smoke_c.c
// Function:		smoke character profile
// Source:			WORR original Q3-style BotLib seed
// Tab Size:		4 (real tabs)
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME					"Smoke"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.41
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/smoke_w.c"
	CHARACTERISTIC_AIM_SKILL			0.43
	CHARACTERISTIC_AIM_ACCURACY			0.43
	CHARACTERISTIC_VIEW_FACTOR			0.64
	CHARACTERISTIC_VIEW_MAXCHANGE		154
	CHARACTERISTIC_REACTIONTIME			1.150

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.41
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.43
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.45
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.41
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.38
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.40
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.47
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.42
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.48
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.44
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.42
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.37

	CHARACTERISTIC_CHAT_FILE			"bots/smoke_t.c"
	CHARACTERISTIC_CHAT_NAME			"smoke"
	CHARACTERISTIC_CHAT_CPM				240
	CHARACTERISTIC_CHAT_INSULT			0.07
	CHARACTERISTIC_CHAT_MISC			0.20
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.13
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.10
	CHARACTERISTIC_CHAT_KILL			0.16
	CHARACTERISTIC_CHAT_DEATH			0.10
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.07
	CHARACTERISTIC_CHAT_HITTALKING		0.03
	CHARACTERISTIC_CHAT_HITNODEATH		0.13
	CHARACTERISTIC_CHAT_HITNOKILL		0.16
	CHARACTERISTIC_CHAT_RANDOM			0.07
	CHARACTERISTIC_CHAT_REPLY			0.13

	CHARACTERISTIC_CROUCHER				0.15
	CHARACTERISTIC_JUMPER				0.45
	CHARACTERISTIC_WEAPONJUMPING		0.29
	CHARACTERISTIC_GRAPPLE_USER			0.16
	CHARACTERISTIC_WALKER				0.22

	CHARACTERISTIC_ITEMWEIGHTS			"bots/smoke_i.c"
	CHARACTERISTIC_AGGRESSION			0.38
	CHARACTERISTIC_SELFPRESERVATION		0.65
	CHARACTERISTIC_VENGEFULNESS			0.36
	CHARACTERISTIC_CAMPER				0.23
	CHARACTERISTIC_EASY_FRAGGER			0.17
	CHARACTERISTIC_ALERTNESS			0.46
	CHARACTERISTIC_FIRETHROTTLE			0.38

	WORR_SKIN							"male/grunt"
	WORR_TEAM							"free"
	WORR_AIM_ERROR						5.50
	WORR_PREFERRED_WEAPON				"rocketlauncher"
	WORR_CHAT_PERSONALITY				"quiet"
	WORR_ROLE							"attacker"
	WORR_MOVEMENT_STYLE					"strafe"
	WORR_REACTION_JITTER_MS				180
	WORR_AIM_TRACKING_NOISE				4.50
	WORR_AIM_LEAD_SCALE					0.80
	WORR_COMBAT_FOV						110
	WORR_TEAMPLAY_BIAS					0.35
	WORR_OBJECTIVE_BIAS					0.55
	WORR_FRIENDLY_FIRE_CARE				0.55
	WORR_ITEM_GREED						0.68
	WORR_ITEM_DENIAL					0.50
	WORR_POWERUP_TIMING					0.70
	WORR_RETREAT_HEALTH					45
} //end skill 1 smoke

skill 3
{
	CHARACTERISTIC_NAME					"Smoke"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.59
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/smoke_w.c"
	CHARACTERISTIC_AIM_SKILL			0.62
	CHARACTERISTIC_AIM_ACCURACY			0.63
	CHARACTERISTIC_VIEW_FACTOR			0.75
	CHARACTERISTIC_VIEW_MAXCHANGE		189
	CHARACTERISTIC_REACTIONTIME			0.550

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.53
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.55
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.58
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.53
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.49
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.51
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.61
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.54
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.61
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.56
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.55
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.48

	CHARACTERISTIC_CHAT_FILE			"bots/smoke_t.c"
	CHARACTERISTIC_CHAT_NAME			"smoke"
	CHARACTERISTIC_CHAT_CPM				288
	CHARACTERISTIC_CHAT_INSULT			0.09
	CHARACTERISTIC_CHAT_MISC			0.26
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.17
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.13
	CHARACTERISTIC_CHAT_KILL			0.21
	CHARACTERISTIC_CHAT_DEATH			0.13
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.09
	CHARACTERISTIC_CHAT_HITTALKING		0.04
	CHARACTERISTIC_CHAT_HITNODEATH		0.17
	CHARACTERISTIC_CHAT_HITNOKILL		0.21
	CHARACTERISTIC_CHAT_RANDOM			0.09
	CHARACTERISTIC_CHAT_REPLY			0.17

	CHARACTERISTIC_CROUCHER				0.15
	CHARACTERISTIC_JUMPER				0.59
	CHARACTERISTIC_WEAPONJUMPING		0.38
	CHARACTERISTIC_GRAPPLE_USER			0.21
	CHARACTERISTIC_WALKER				0.14

	CHARACTERISTIC_ITEMWEIGHTS			"bots/smoke_i.c"
	CHARACTERISTIC_AGGRESSION			0.55
	CHARACTERISTIC_SELFPRESERVATION		0.59
	CHARACTERISTIC_VENGEFULNESS			0.51
	CHARACTERISTIC_CAMPER				0.18
	CHARACTERISTIC_EASY_FRAGGER			0.25
	CHARACTERISTIC_ALERTNESS			0.67
	CHARACTERISTIC_FIRETHROTTLE			0.55

	WORR_SKIN							"male/grunt"
	WORR_TEAM							"free"
	WORR_AIM_ERROR						3.50
	WORR_PREFERRED_WEAPON				"rocketlauncher"
	WORR_CHAT_PERSONALITY				"quiet"
	WORR_ROLE							"attacker"
	WORR_MOVEMENT_STYLE					"strafe"
	WORR_REACTION_JITTER_MS				120
	WORR_AIM_TRACKING_NOISE				2.70
	WORR_AIM_LEAD_SCALE					0.95
	WORR_COMBAT_FOV						125
	WORR_TEAMPLAY_BIAS					0.42
	WORR_OBJECTIVE_BIAS					0.65
	WORR_FRIENDLY_FIRE_CARE				0.62
	WORR_ITEM_GREED						0.72
	WORR_ITEM_DENIAL					0.60
	WORR_POWERUP_TIMING					0.80
	WORR_RETREAT_HEALTH					38
} //end skill 3 smoke

skill 4
{
	CHARACTERISTIC_NAME					"Smoke"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.70
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/smoke_w.c"
	CHARACTERISTIC_AIM_SKILL			0.74
	CHARACTERISTIC_AIM_ACCURACY			0.75
	CHARACTERISTIC_VIEW_FACTOR			0.82
	CHARACTERISTIC_VIEW_MAXCHANGE		220
	CHARACTERISTIC_REACTIONTIME			0.250

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.58
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.61
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.65
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.58
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.54
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.57
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.68
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.60
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.68
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.62
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.61
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.53

	CHARACTERISTIC_CHAT_FILE			"bots/smoke_t.c"
	CHARACTERISTIC_CHAT_NAME			"smoke"
	CHARACTERISTIC_CHAT_CPM				320
	CHARACTERISTIC_CHAT_INSULT			0.10
	CHARACTERISTIC_CHAT_MISC			0.30
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.20
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.15
	CHARACTERISTIC_CHAT_KILL			0.25
	CHARACTERISTIC_CHAT_DEATH			0.15
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.10
	CHARACTERISTIC_CHAT_HITTALKING		0.05
	CHARACTERISTIC_CHAT_HITNODEATH		0.20
	CHARACTERISTIC_CHAT_HITNOKILL		0.25
	CHARACTERISTIC_CHAT_RANDOM			0.10
	CHARACTERISTIC_CHAT_REPLY			0.20

	CHARACTERISTIC_CROUCHER				0.15
	CHARACTERISTIC_JUMPER				0.70
	CHARACTERISTIC_WEAPONJUMPING		0.45
	CHARACTERISTIC_GRAPPLE_USER			0.25
	CHARACTERISTIC_WALKER				0.10

	CHARACTERISTIC_ITEMWEIGHTS			"bots/smoke_i.c"
	CHARACTERISTIC_AGGRESSION			0.65
	CHARACTERISTIC_SELFPRESERVATION		0.55
	CHARACTERISTIC_VENGEFULNESS			0.60
	CHARACTERISTIC_CAMPER				0.15
	CHARACTERISTIC_EASY_FRAGGER			0.30
	CHARACTERISTIC_ALERTNESS			0.80
	CHARACTERISTIC_FIRETHROTTLE			0.65

	WORR_SKIN							"male/grunt"
	WORR_TEAM							"free"
	WORR_AIM_ERROR						2.50
	WORR_PREFERRED_WEAPON				"rocketlauncher"
	WORR_CHAT_PERSONALITY				"quiet"
	WORR_ROLE							"attacker"
	WORR_MOVEMENT_STYLE					"strafe"
	WORR_REACTION_JITTER_MS				80
	WORR_AIM_TRACKING_NOISE				1.80
	WORR_AIM_LEAD_SCALE					1.05
	WORR_COMBAT_FOV						135
	WORR_TEAMPLAY_BIAS					0.48
	WORR_OBJECTIVE_BIAS					0.72
	WORR_FRIENDLY_FIRE_CARE				0.68
	WORR_ITEM_GREED						0.76
	WORR_ITEM_DENIAL					0.70
	WORR_POWERUP_TIMING					0.88
	WORR_RETREAT_HEALTH					32
} //end skill 4 smoke

