//===========================================================================
//
// Name:			vanguard_c.c
// Function:		vanguard character profile
// Source:			WORR original Q3-style BotLib seed
// Tab Size:		4 (real tabs)
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME					"Vanguard"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.51
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/vanguard_w.c"
	CHARACTERISTIC_AIM_SKILL			0.49
	CHARACTERISTIC_AIM_ACCURACY			0.48
	CHARACTERISTIC_VIEW_FACTOR			0.72
	CHARACTERISTIC_VIEW_MAXCHANGE		182
	CHARACTERISTIC_REACTIONTIME			1.080

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.45
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.47
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.49
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.45
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.41
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.44
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.52
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.46
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.54
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.49
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.48
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.42

	CHARACTERISTIC_CHAT_FILE			"bots/vanguard_t.c"
	CHARACTERISTIC_CHAT_NAME			"vanguard"
	CHARACTERISTIC_CHAT_CPM				270
	CHARACTERISTIC_CHAT_INSULT			0.26
	CHARACTERISTIC_CHAT_MISC			0.29
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.23
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.20
	CHARACTERISTIC_CHAT_KILL			0.36
	CHARACTERISTIC_CHAT_DEATH			0.13
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.16
	CHARACTERISTIC_CHAT_HITTALKING		0.10
	CHARACTERISTIC_CHAT_HITNODEATH		0.29
	CHARACTERISTIC_CHAT_HITNOKILL		0.29
	CHARACTERISTIC_CHAT_RANDOM			0.20
	CHARACTERISTIC_CHAT_REPLY			0.16

	CHARACTERISTIC_CROUCHER				0.05
	CHARACTERISTIC_JUMPER				0.49
	CHARACTERISTIC_WEAPONJUMPING		0.36
	CHARACTERISTIC_GRAPPLE_USER			0.20
	CHARACTERISTIC_WALKER				0.17

	CHARACTERISTIC_ITEMWEIGHTS			"bots/vanguard_i.c"
	CHARACTERISTIC_AGGRESSION			0.48
	CHARACTERISTIC_SELFPRESERVATION		0.45
	CHARACTERISTIC_VENGEFULNESS			0.48
	CHARACTERISTIC_CAMPER				0.13
	CHARACTERISTIC_EASY_FRAGGER			0.32
	CHARACTERISTIC_ALERTNESS			0.51
	CHARACTERISTIC_FIRETHROTTLE			0.52

	WORR_SKIN							"male/major"
	WORR_TEAM							"red"
	WORR_AIM_ERROR						4.80
	WORR_PREFERRED_WEAPON				"chaingun"
	WORR_CHAT_PERSONALITY				"direct"
	WORR_ROLE							"attacker"
	WORR_MOVEMENT_STYLE					"pressure"
	WORR_REACTION_JITTER_MS				160
	WORR_AIM_TRACKING_NOISE				3.80
	WORR_AIM_LEAD_SCALE					0.85
	WORR_COMBAT_FOV						115
	WORR_TEAMPLAY_BIAS					0.55
	WORR_OBJECTIVE_BIAS					0.70
	WORR_FRIENDLY_FIRE_CARE				0.50
	WORR_ITEM_GREED						0.62
	WORR_ITEM_DENIAL					0.65
	WORR_POWERUP_TIMING					0.70
	WORR_RETREAT_HEALTH					35
} //end skill 1 vanguard

skill 4
{
	CHARACTERISTIC_NAME					"Vanguard"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.74
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/vanguard_w.c"
	CHARACTERISTIC_AIM_SKILL			0.71
	CHARACTERISTIC_AIM_ACCURACY			0.69
	CHARACTERISTIC_VIEW_FACTOR			0.85
	CHARACTERISTIC_VIEW_MAXCHANGE		224
	CHARACTERISTIC_REACTIONTIME			0.480

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.58
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.61
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.63
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.58
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.53
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.56
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.66
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.59
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.70
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.64
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.62
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.54

	CHARACTERISTIC_CHAT_FILE			"bots/vanguard_t.c"
	CHARACTERISTIC_CHAT_NAME			"vanguard"
	CHARACTERISTIC_CHAT_CPM				324
	CHARACTERISTIC_CHAT_INSULT			0.34
	CHARACTERISTIC_CHAT_MISC			0.38
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.30
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.26
	CHARACTERISTIC_CHAT_KILL			0.47
	CHARACTERISTIC_CHAT_DEATH			0.17
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.21
	CHARACTERISTIC_CHAT_HITTALKING		0.13
	CHARACTERISTIC_CHAT_HITNODEATH		0.38
	CHARACTERISTIC_CHAT_HITNOKILL		0.38
	CHARACTERISTIC_CHAT_RANDOM			0.26
	CHARACTERISTIC_CHAT_REPLY			0.21

	CHARACTERISTIC_CROUCHER				0.05
	CHARACTERISTIC_JUMPER				0.64
	CHARACTERISTIC_WEAPONJUMPING		0.47
	CHARACTERISTIC_GRAPPLE_USER			0.26
	CHARACTERISTIC_WALKER				0.09

	CHARACTERISTIC_ITEMWEIGHTS			"bots/vanguard_i.c"
	CHARACTERISTIC_AGGRESSION			0.69
	CHARACTERISTIC_SELFPRESERVATION		0.39
	CHARACTERISTIC_VENGEFULNESS			0.68
	CHARACTERISTIC_CAMPER				0.08
	CHARACTERISTIC_EASY_FRAGGER			0.46
	CHARACTERISTIC_ALERTNESS			0.74
	CHARACTERISTIC_FIRETHROTTLE			0.76

	WORR_SKIN							"male/major"
	WORR_TEAM							"red"
	WORR_AIM_ERROR						2.80
	WORR_PREFERRED_WEAPON				"chaingun"
	WORR_CHAT_PERSONALITY				"direct"
	WORR_ROLE							"attacker"
	WORR_MOVEMENT_STYLE					"pressure"
	WORR_REACTION_JITTER_MS				100
	WORR_AIM_TRACKING_NOISE				2.40
	WORR_AIM_LEAD_SCALE					1.00
	WORR_COMBAT_FOV						130
	WORR_TEAMPLAY_BIAS					0.62
	WORR_OBJECTIVE_BIAS					0.78
	WORR_FRIENDLY_FIRE_CARE				0.62
	WORR_ITEM_GREED						0.68
	WORR_ITEM_DENIAL					0.78
	WORR_POWERUP_TIMING					0.82
	WORR_RETREAT_HEALTH					30
} //end skill 4 vanguard

skill 5
{
	CHARACTERISTIC_NAME					"Vanguard"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.88
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/vanguard_w.c"
	CHARACTERISTIC_AIM_SKILL			0.84
	CHARACTERISTIC_AIM_ACCURACY			0.82
	CHARACTERISTIC_VIEW_FACTOR			0.92
	CHARACTERISTIC_VIEW_MAXCHANGE		260
	CHARACTERISTIC_REACTIONTIME			0.180

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.64
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.67
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.71
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.64
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.59
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.62
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.74
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.66
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.77
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.71
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.69
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.60

	CHARACTERISTIC_CHAT_FILE			"bots/vanguard_t.c"
	CHARACTERISTIC_CHAT_NAME			"vanguard"
	CHARACTERISTIC_CHAT_CPM				360
	CHARACTERISTIC_CHAT_INSULT			0.40
	CHARACTERISTIC_CHAT_MISC			0.45
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.35
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.30
	CHARACTERISTIC_CHAT_KILL			0.55
	CHARACTERISTIC_CHAT_DEATH			0.20
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.25
	CHARACTERISTIC_CHAT_HITTALKING		0.15
	CHARACTERISTIC_CHAT_HITNODEATH		0.45
	CHARACTERISTIC_CHAT_HITNOKILL		0.45
	CHARACTERISTIC_CHAT_RANDOM			0.30
	CHARACTERISTIC_CHAT_REPLY			0.25

	CHARACTERISTIC_CROUCHER				0.05
	CHARACTERISTIC_JUMPER				0.75
	CHARACTERISTIC_WEAPONJUMPING		0.55
	CHARACTERISTIC_GRAPPLE_USER			0.30
	CHARACTERISTIC_WALKER				0.05

	CHARACTERISTIC_ITEMWEIGHTS			"bots/vanguard_i.c"
	CHARACTERISTIC_AGGRESSION			0.82
	CHARACTERISTIC_SELFPRESERVATION		0.35
	CHARACTERISTIC_VENGEFULNESS			0.80
	CHARACTERISTIC_CAMPER				0.05
	CHARACTERISTIC_EASY_FRAGGER			0.55
	CHARACTERISTIC_ALERTNESS			0.88
	CHARACTERISTIC_FIRETHROTTLE			0.90

	WORR_SKIN							"male/major"
	WORR_TEAM							"red"
	WORR_AIM_ERROR						1.80
	WORR_PREFERRED_WEAPON				"chaingun"
	WORR_CHAT_PERSONALITY				"direct"
	WORR_ROLE							"attacker"
	WORR_MOVEMENT_STYLE					"pressure"
	WORR_REACTION_JITTER_MS				60
	WORR_AIM_TRACKING_NOISE				1.50
	WORR_AIM_LEAD_SCALE					1.10
	WORR_COMBAT_FOV						145
	WORR_TEAMPLAY_BIAS					0.70
	WORR_OBJECTIVE_BIAS					0.86
	WORR_FRIENDLY_FIRE_CARE				0.72
	WORR_ITEM_GREED						0.74
	WORR_ITEM_DENIAL					0.88
	WORR_POWERUP_TIMING					0.92
	WORR_RETREAT_HEALTH					25
} //end skill 5 vanguard

