//===========================================================================
//
// Name:			vector_c.c
// Function:		vector character profile
// Source:			WORR original Q3-style BotLib seed
// Tab Size:		4 (real tabs)
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME					"Vector"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.45
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/vector_w.c"
	CHARACTERISTIC_AIM_SKILL			0.46
	CHARACTERISTIC_AIM_ACCURACY			0.45
	CHARACTERISTIC_VIEW_FACTOR			0.69
	CHARACTERISTIC_VIEW_MAXCHANGE		168
	CHARACTERISTIC_REACTIONTIME			1.110

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.43
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.45
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.47
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.43
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.39
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.41
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.49
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.44
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.52
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.47
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.46
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.40

	CHARACTERISTIC_CHAT_FILE			"bots/vector_t.c"
	CHARACTERISTIC_CHAT_NAME			"vector"
	CHARACTERISTIC_CHAT_CPM				285
	CHARACTERISTIC_CHAT_INSULT			0.33
	CHARACTERISTIC_CHAT_MISC			0.23
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.20
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.16
	CHARACTERISTIC_CHAT_KILL			0.33
	CHARACTERISTIC_CHAT_DEATH			0.16
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.20
	CHARACTERISTIC_CHAT_HITTALKING		0.13
	CHARACTERISTIC_CHAT_HITNODEATH		0.33
	CHARACTERISTIC_CHAT_HITNOKILL		0.33
	CHARACTERISTIC_CHAT_RANDOM			0.20
	CHARACTERISTIC_CHAT_REPLY			0.13

	CHARACTERISTIC_CROUCHER				0.10
	CHARACTERISTIC_JUMPER				0.55
	CHARACTERISTIC_WEAPONJUMPING		0.42
	CHARACTERISTIC_GRAPPLE_USER			0.13
	CHARACTERISTIC_WALKER				0.17

	CHARACTERISTIC_ITEMWEIGHTS			"bots/vector_i.c"
	CHARACTERISTIC_AGGRESSION			0.43
	CHARACTERISTIC_SELFPRESERVATION		0.80
	CHARACTERISTIC_VENGEFULNESS			0.42
	CHARACTERISTIC_CAMPER				0.18
	CHARACTERISTIC_EASY_FRAGGER			0.26
	CHARACTERISTIC_ALERTNESS			0.53
	CHARACTERISTIC_FIRETHROTTLE			0.41

	WORR_SKIN							"male/grunt"
	WORR_TEAM							"free"
	WORR_AIM_ERROR						5.20
	WORR_PREFERRED_WEAPON				"railgun"
	WORR_CHAT_PERSONALITY				"taunting"
	WORR_ROLE							"duelist"
	WORR_MOVEMENT_STYLE					"kite"
	WORR_REACTION_JITTER_MS				150
	WORR_AIM_TRACKING_NOISE				3.20
	WORR_AIM_LEAD_SCALE					0.90
	WORR_COMBAT_FOV						125
	WORR_TEAMPLAY_BIAS					0.30
	WORR_OBJECTIVE_BIAS					0.50
	WORR_FRIENDLY_FIRE_CARE				0.55
	WORR_ITEM_GREED						0.64
	WORR_ITEM_DENIAL					0.60
	WORR_POWERUP_TIMING					0.65
	WORR_RETREAT_HEALTH					42
} //end skill 1 vector

skill 3
{
	CHARACTERISTIC_NAME					"Vector"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.66
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/vector_w.c"
	CHARACTERISTIC_AIM_SKILL			0.67
	CHARACTERISTIC_AIM_ACCURACY			0.66
	CHARACTERISTIC_VIEW_FACTOR			0.81
	CHARACTERISTIC_VIEW_MAXCHANGE		206
	CHARACTERISTIC_REACTIONTIME			0.510

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.55
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.58
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.60
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.55
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.51
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.53
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.63
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.56
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.66
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.60
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.59
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.52

	CHARACTERISTIC_CHAT_FILE			"bots/vector_t.c"
	CHARACTERISTIC_CHAT_NAME			"vector"
	CHARACTERISTIC_CHAT_CPM				342
	CHARACTERISTIC_CHAT_INSULT			0.42
	CHARACTERISTIC_CHAT_MISC			0.30
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.26
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.21
	CHARACTERISTIC_CHAT_KILL			0.42
	CHARACTERISTIC_CHAT_DEATH			0.21
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.26
	CHARACTERISTIC_CHAT_HITTALKING		0.17
	CHARACTERISTIC_CHAT_HITNODEATH		0.42
	CHARACTERISTIC_CHAT_HITNOKILL		0.42
	CHARACTERISTIC_CHAT_RANDOM			0.26
	CHARACTERISTIC_CHAT_REPLY			0.17

	CHARACTERISTIC_CROUCHER				0.10
	CHARACTERISTIC_JUMPER				0.72
	CHARACTERISTIC_WEAPONJUMPING		0.55
	CHARACTERISTIC_GRAPPLE_USER			0.17
	CHARACTERISTIC_WALKER				0.09

	CHARACTERISTIC_ITEMWEIGHTS			"bots/vector_i.c"
	CHARACTERISTIC_AGGRESSION			0.62
	CHARACTERISTIC_SELFPRESERVATION		0.74
	CHARACTERISTIC_VENGEFULNESS			0.59
	CHARACTERISTIC_CAMPER				0.13
	CHARACTERISTIC_EASY_FRAGGER			0.38
	CHARACTERISTIC_ALERTNESS			0.77
	CHARACTERISTIC_FIRETHROTTLE			0.59

	WORR_SKIN							"male/grunt"
	WORR_TEAM							"free"
	WORR_AIM_ERROR						3.20
	WORR_PREFERRED_WEAPON				"railgun"
	WORR_CHAT_PERSONALITY				"taunting"
	WORR_ROLE							"duelist"
	WORR_MOVEMENT_STYLE					"kite"
	WORR_REACTION_JITTER_MS				95
	WORR_AIM_TRACKING_NOISE				2.00
	WORR_AIM_LEAD_SCALE					1.02
	WORR_COMBAT_FOV						140
	WORR_TEAMPLAY_BIAS					0.38
	WORR_OBJECTIVE_BIAS					0.58
	WORR_FRIENDLY_FIRE_CARE				0.65
	WORR_ITEM_GREED						0.70
	WORR_ITEM_DENIAL					0.72
	WORR_POWERUP_TIMING					0.78
	WORR_RETREAT_HEALTH					36
} //end skill 3 vector

skill 4
{
	CHARACTERISTIC_NAME					"Vector"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.78
	CHARACTERISTIC_WEAPONWEIGHTS		"bots/vector_w.c"
	CHARACTERISTIC_AIM_SKILL			0.80
	CHARACTERISTIC_AIM_ACCURACY			0.78
	CHARACTERISTIC_VIEW_FACTOR			0.88
	CHARACTERISTIC_VIEW_MAXCHANGE		240
	CHARACTERISTIC_REACTIONTIME			0.210

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	0.61
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN	0.64
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.67
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.61
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING	0.56
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN	0.59
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN	0.70
	CHARACTERISTIC_AIM_ACCURACY_BFG10K	0.62
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.74
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER		0.67
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN		0.66
	CHARACTERISTIC_AIM_SKILL_BFG10K		0.58

	CHARACTERISTIC_CHAT_FILE			"bots/vector_t.c"
	CHARACTERISTIC_CHAT_NAME			"vector"
	CHARACTERISTIC_CHAT_CPM				380
	CHARACTERISTIC_CHAT_INSULT			0.50
	CHARACTERISTIC_CHAT_MISC			0.35
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.30
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.25
	CHARACTERISTIC_CHAT_KILL			0.50
	CHARACTERISTIC_CHAT_DEATH			0.25
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.30
	CHARACTERISTIC_CHAT_HITTALKING		0.20
	CHARACTERISTIC_CHAT_HITNODEATH		0.50
	CHARACTERISTIC_CHAT_HITNOKILL		0.50
	CHARACTERISTIC_CHAT_RANDOM			0.30
	CHARACTERISTIC_CHAT_REPLY			0.20

	CHARACTERISTIC_CROUCHER				0.10
	CHARACTERISTIC_JUMPER				0.85
	CHARACTERISTIC_WEAPONJUMPING		0.65
	CHARACTERISTIC_GRAPPLE_USER			0.20
	CHARACTERISTIC_WALKER				0.05

	CHARACTERISTIC_ITEMWEIGHTS			"bots/vector_i.c"
	CHARACTERISTIC_AGGRESSION			0.74
	CHARACTERISTIC_SELFPRESERVATION		0.70
	CHARACTERISTIC_VENGEFULNESS			0.70
	CHARACTERISTIC_CAMPER				0.10
	CHARACTERISTIC_EASY_FRAGGER			0.45
	CHARACTERISTIC_ALERTNESS			0.92
	CHARACTERISTIC_FIRETHROTTLE			0.70

	WORR_SKIN							"male/grunt"
	WORR_TEAM							"free"
	WORR_AIM_ERROR						2.20
	WORR_PREFERRED_WEAPON				"railgun"
	WORR_CHAT_PERSONALITY				"taunting"
	WORR_ROLE							"duelist"
	WORR_MOVEMENT_STYLE					"kite"
	WORR_REACTION_JITTER_MS				55
	WORR_AIM_TRACKING_NOISE				1.20
	WORR_AIM_LEAD_SCALE					1.12
	WORR_COMBAT_FOV						150
	WORR_TEAMPLAY_BIAS					0.45
	WORR_OBJECTIVE_BIAS					0.65
	WORR_FRIENDLY_FIRE_CARE				0.75
	WORR_ITEM_GREED						0.76
	WORR_ITEM_DENIAL					0.84
	WORR_POWERUP_TIMING					0.90
	WORR_RETREAT_HEALTH					30
} //end skill 4 vector

