/*
Copyright (C) 2026 WORR contributors

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
*/

#include "shared/local_action_weapon_semantics.h"

#include "shared/local_action_weapon_profile.h"

#include <string.h>

#define EM_PROJECTILE WORR_LOCAL_ACTION_WEAPON_EMISSION_STRAIGHT_PROJECTILE
#define EM_BALLISTIC WORR_LOCAL_ACTION_WEAPON_EMISSION_BALLISTIC_PROJECTILE
#define EM_DEPLOYABLE                                                          \
  (WORR_LOCAL_ACTION_WEAPON_EMISSION_BALLISTIC_PROJECTILE |                    \
   WORR_LOCAL_ACTION_WEAPON_EMISSION_DEPLOYABLE)
#define DEP_PROJECTILE                                                         \
  (WORR_LOCAL_ACTION_WEAPON_DEP_SERVER_ENTITY |                                \
   WORR_LOCAL_ACTION_WEAPON_DEP_POWERUP_STATE)
#define DEP_AMMO                                                               \
  (WORR_LOCAL_ACTION_WEAPON_DEP_INVENTORY |                                    \
   WORR_LOCAL_ACTION_WEAPON_DEP_INFINITE_AMMO_POLICY)
#define DEP_HISTORICAL                                                         \
  (WORR_LOCAL_ACTION_WEAPON_DEP_WORLD_QUERY |                                  \
   WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION)
#define BLOCK_COMMON                                                           \
  (WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_COMMAND_TIME_OWNERSHIP |                  \
   WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_LEGACY_FRAME_TIMELINE |                   \
   WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_WORLD_AUTHORITY |                         \
   WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_ASSET_EVENT_MAPPING)
#define BLOCK_PROJECTILE                                                       \
  (WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_SERVER_ENTITY_LIFECYCLE)
#define BLOCK_HISTORICAL (WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_HISTORICAL_QUERY)
#define BLOCK_REPEAT                                                           \
  (WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_HELD_REPEAT |                             \
   WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_EXTERNAL_CLIENT_STATE)

#define S(id, trigger, emission, deps, behavior, ammo_min, ammo_max,           \
          emission_min, emission_max, blockers)                                \
  {sizeof(worr_local_action_weapon_semantics_v1),                              \
   WORR_LOCAL_ACTION_WEAPON_SEMANTICS_ABI_VERSION,                             \
   WORR_LOCAL_ACTION_WEAPON_SEMANTICS_MODEL_REVISION,                          \
   (id),                                                                       \
   (trigger),                                                                  \
   (emission),                                                                 \
   (deps),                                                                     \
   (behavior),                                                                 \
   (ammo_min),                                                                 \
   (ammo_max),                                                                 \
   (emission_min),                                                             \
   (emission_max),                                                             \
   (blockers),                                                                 \
   WORR_LOCAL_ACTION_CATALOG_MODEL_REVISION,                                   \
   WORR_LOCAL_ACTION_WEAPON_PROFILE_MODEL_REVISION,                            \
   0}

static const worr_local_action_weapon_semantics_v1 semantics[] = {
    S(WORR_LOCAL_ACTION_CATALOG_BLASTER,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS, EM_PROJECTILE,
      DEP_PROJECTILE | WORR_LOCAL_ACTION_WEAPON_DEP_RULESET, 0, 0, 0, 1, 1,
      BLOCK_COMMON | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RULESET_BRANCH),
    S(WORR_LOCAL_ACTION_CATALOG_CHAINFIST,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_HELD_REPEAT,
      WORR_LOCAL_ACTION_WEAPON_EMISSION_MELEE_TRACE | EM_BALLISTIC,
      WORR_LOCAL_ACTION_WEAPON_DEP_WORLD_QUERY |
          WORR_LOCAL_ACTION_WEAPON_DEP_SERVER_ENTITY |
          WORR_LOCAL_ACTION_WEAPON_DEP_GAME_MODE |
          WORR_LOCAL_ACTION_WEAPON_DEP_POWERUP_STATE |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE |
          WORR_LOCAL_ACTION_WEAPON_DEP_SERVER_TIME |
          WORR_LOCAL_ACTION_WEAPON_DEP_OBJECTIVE_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_LOOPING_FRAME_MACHINE |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_MODE_OVERRIDE,
      0, 0, 0, 1,
      BLOCK_COMMON | BLOCK_REPEAT | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_MODE_OVERRIDE),
    S(WORR_LOCAL_ACTION_CATALOG_SHOTGUN,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS,
      WORR_LOCAL_ACTION_WEAPON_EMISSION_HITSCAN,
      DEP_AMMO | DEP_HISTORICAL | WORR_LOCAL_ACTION_WEAPON_DEP_RANDOM_STREAM |
          WORR_LOCAL_ACTION_WEAPON_DEP_RULESET |
          WORR_LOCAL_ACTION_WEAPON_DEP_POWERUP_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_RANDOMIZED_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_MULTI_EMISSION,
      1, 1, 11, 12,
      BLOCK_COMMON | BLOCK_HISTORICAL |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RULESET_BRANCH |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RANDOM_STREAM),
    S(WORR_LOCAL_ACTION_CATALOG_SUPER_SHOTGUN,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS,
      WORR_LOCAL_ACTION_WEAPON_EMISSION_HITSCAN,
      DEP_AMMO | DEP_HISTORICAL | WORR_LOCAL_ACTION_WEAPON_DEP_RANDOM_STREAM |
          WORR_LOCAL_ACTION_WEAPON_DEP_POWERUP_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_RANDOMIZED_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_MULTI_EMISSION,
      2, 2, 20, 20,
      BLOCK_COMMON | BLOCK_HISTORICAL |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RANDOM_STREAM),
    S(WORR_LOCAL_ACTION_CATALOG_MACHINEGUN,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_HELD_REPEAT,
      WORR_LOCAL_ACTION_WEAPON_EMISSION_HITSCAN,
      DEP_AMMO | DEP_HISTORICAL | WORR_LOCAL_ACTION_WEAPON_DEP_RANDOM_STREAM |
          WORR_LOCAL_ACTION_WEAPON_DEP_RULESET |
          WORR_LOCAL_ACTION_WEAPON_DEP_GAME_MODE |
          WORR_LOCAL_ACTION_WEAPON_DEP_POWERUP_STATE |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_RANDOMIZED_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_LOOPING_FRAME_MACHINE,
      0, 1, 0, 1,
      BLOCK_COMMON | BLOCK_REPEAT | BLOCK_HISTORICAL |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RULESET_BRANCH |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RANDOM_STREAM),
    S(WORR_LOCAL_ACTION_CATALOG_ETF_RIFLE,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_HELD_REPEAT, EM_PROJECTILE,
      DEP_AMMO | DEP_PROJECTILE | WORR_LOCAL_ACTION_WEAPON_DEP_RANDOM_STREAM |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_RANDOMIZED_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_LOOPING_FRAME_MACHINE |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_ALTERNATING_MUZZLE,
      0, 1, 0, 1,
      BLOCK_COMMON | BLOCK_REPEAT | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RANDOM_STREAM),
    S(WORR_LOCAL_ACTION_CATALOG_CHAINGUN,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SPIN_REPEAT,
      WORR_LOCAL_ACTION_WEAPON_EMISSION_HITSCAN,
      DEP_AMMO | DEP_HISTORICAL | WORR_LOCAL_ACTION_WEAPON_DEP_RANDOM_STREAM |
          WORR_LOCAL_ACTION_WEAPON_DEP_GAME_MODE |
          WORR_LOCAL_ACTION_WEAPON_DEP_POWERUP_STATE |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_RANDOMIZED_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_MULTI_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_LOOPING_FRAME_MACHINE |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONTINUOUS_PRESENTATION,
      0, 3, 0, 3,
      BLOCK_COMMON | BLOCK_REPEAT | BLOCK_HISTORICAL |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RANDOM_STREAM),
    S(WORR_LOCAL_ACTION_CATALOG_HAND_GRENADES,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_THROW_HOLD_RELEASE, EM_BALLISTIC,
      DEP_AMMO | DEP_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION |
          WORR_LOCAL_ACTION_WEAPON_DEP_HOLD_TIME |
          WORR_LOCAL_ACTION_WEAPON_DEP_PLAYER_HEALTH |
          WORR_LOCAL_ACTION_WEAPON_DEP_SERVER_TIME,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_HOLD_RELEASE |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_COOK_IN_HAND |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_HOLD_SCALED_TRAJECTORY,
      1, 1, 1, 1,
      BLOCK_COMMON | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_HOLD_RELEASE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_EXTERNAL_CLIENT_STATE),
    S(WORR_LOCAL_ACTION_CATALOG_TRAP,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_THROW_HOLD_RELEASE, EM_DEPLOYABLE,
      DEP_AMMO | DEP_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION |
          WORR_LOCAL_ACTION_WEAPON_DEP_HOLD_TIME |
          WORR_LOCAL_ACTION_WEAPON_DEP_PLAYER_HEALTH |
          WORR_LOCAL_ACTION_WEAPON_DEP_SERVER_TIME,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_HOLD_RELEASE |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_HOLD_SCALED_TRAJECTORY,
      1, 1, 1, 1,
      BLOCK_COMMON | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_HOLD_RELEASE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_EXTERNAL_CLIENT_STATE),
    S(WORR_LOCAL_ACTION_CATALOG_TESLA_MINE,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_THROW_HOLD_RELEASE, EM_DEPLOYABLE,
      DEP_AMMO | DEP_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION |
          WORR_LOCAL_ACTION_WEAPON_DEP_HOLD_TIME |
          WORR_LOCAL_ACTION_WEAPON_DEP_PLAYER_HEALTH |
          WORR_LOCAL_ACTION_WEAPON_DEP_SERVER_TIME,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_HOLD_RELEASE |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_HOLD_SCALED_TRAJECTORY,
      1, 1, 1, 1,
      BLOCK_COMMON | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_HOLD_RELEASE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_EXTERNAL_CLIENT_STATE),
    S(WORR_LOCAL_ACTION_CATALOG_GRENADE_LAUNCHER,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS, EM_BALLISTIC,
      DEP_AMMO | DEP_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION |
          WORR_LOCAL_ACTION_WEAPON_DEP_RANDOM_STREAM |
          WORR_LOCAL_ACTION_WEAPON_DEP_RULESET,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_RANDOMIZED_EMISSION, 1, 1, 1, 1,
      BLOCK_COMMON | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RULESET_BRANCH |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RANDOM_STREAM),
    S(WORR_LOCAL_ACTION_CATALOG_PROX_LAUNCHER,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS, EM_DEPLOYABLE,
      DEP_AMMO | DEP_PROJECTILE | WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION,
      0, 1, 1, 1, 1, BLOCK_COMMON | BLOCK_PROJECTILE),
    S(WORR_LOCAL_ACTION_CATALOG_ROCKET_LAUNCHER,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS, EM_PROJECTILE,
      DEP_AMMO | DEP_PROJECTILE | WORR_LOCAL_ACTION_WEAPON_DEP_RULESET |
          WORR_LOCAL_ACTION_WEAPON_DEP_CVAR_POLICY,
      0, 1, 1, 1, 1,
      BLOCK_COMMON | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RULESET_BRANCH),
    S(WORR_LOCAL_ACTION_CATALOG_HYPERBLASTER,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_HELD_REPEAT, EM_PROJECTILE,
      DEP_AMMO | DEP_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION |
          WORR_LOCAL_ACTION_WEAPON_DEP_RANDOM_STREAM |
          WORR_LOCAL_ACTION_WEAPON_DEP_RULESET |
          WORR_LOCAL_ACTION_WEAPON_DEP_GAME_MODE |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_LOOPING_FRAME_MACHINE |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONTINUOUS_PRESENTATION,
      0, 1, 0, 1,
      BLOCK_COMMON | BLOCK_REPEAT | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RULESET_BRANCH |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RANDOM_STREAM),
    S(WORR_LOCAL_ACTION_CATALOG_ION_RIPPER,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS, EM_PROJECTILE,
      DEP_AMMO | WORR_LOCAL_ACTION_WEAPON_DEP_SERVER_ENTITY |
          WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION |
          WORR_LOCAL_ACTION_WEAPON_DEP_RANDOM_STREAM |
          WORR_LOCAL_ACTION_WEAPON_DEP_SERVER_TIME,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_RANDOMIZED_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_MULTI_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CUSTOM_REFIRE,
      0, 10, 0, 15,
      BLOCK_COMMON | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_EXTERNAL_CLIENT_STATE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RANDOM_STREAM),
    S(WORR_LOCAL_ACTION_CATALOG_PLASMA_GUN,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_HELD_REPEAT, EM_PROJECTILE,
      DEP_AMMO | DEP_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_LOOPING_FRAME_MACHINE,
      0, 1, 0, 1,
      BLOCK_COMMON | BLOCK_REPEAT | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION),
    S(WORR_LOCAL_ACTION_CATALOG_PLASMA_BEAM,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_HELD_REPEAT,
      WORR_LOCAL_ACTION_WEAPON_EMISSION_CONTINUOUS_BEAM,
      DEP_AMMO | DEP_HISTORICAL | WORR_LOCAL_ACTION_WEAPON_DEP_RULESET |
          WORR_LOCAL_ACTION_WEAPON_DEP_GAME_MODE |
          WORR_LOCAL_ACTION_WEAPON_DEP_POWERUP_STATE |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_LOOPING_FRAME_MACHINE |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONTINUOUS_PRESENTATION,
      0, 2, 0, 1,
      BLOCK_COMMON | BLOCK_REPEAT | BLOCK_HISTORICAL |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RULESET_BRANCH),
    S(WORR_LOCAL_ACTION_CATALOG_THUNDERBOLT,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_HELD_REPEAT,
      WORR_LOCAL_ACTION_WEAPON_EMISSION_CONTINUOUS_BEAM |
          WORR_LOCAL_ACTION_WEAPON_EMISSION_AREA_DISCHARGE,
      DEP_AMMO | DEP_HISTORICAL | WORR_LOCAL_ACTION_WEAPON_DEP_RULESET |
          WORR_LOCAL_ACTION_WEAPON_DEP_GAME_MODE |
          WORR_LOCAL_ACTION_WEAPON_DEP_POWERUP_STATE |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE |
          WORR_LOCAL_ACTION_WEAPON_DEP_WATER_CONTENTS |
          WORR_LOCAL_ACTION_WEAPON_DEP_SERVER_TIME,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_LOOPING_FRAME_MACHINE |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONTINUOUS_PRESENTATION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_DISCHARGE_BRANCH,
      0, 1, 0, 1,
      BLOCK_COMMON | BLOCK_REPEAT | BLOCK_HISTORICAL |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RULESET_BRANCH),
    S(WORR_LOCAL_ACTION_CATALOG_RAILGUN,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS,
      WORR_LOCAL_ACTION_WEAPON_EMISSION_PIERCING_BEAM,
      DEP_AMMO | DEP_HISTORICAL | WORR_LOCAL_ACTION_WEAPON_DEP_GAME_MODE |
          WORR_LOCAL_ACTION_WEAPON_DEP_POWERUP_STATE,
      0, 1, 1, 1, 1, BLOCK_COMMON | BLOCK_HISTORICAL),
    S(WORR_LOCAL_ACTION_CATALOG_PHALANX,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_STAGED_MULTI_FRAME, EM_PROJECTILE,
      DEP_AMMO | DEP_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_MULTI_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_MULTI_FIRE_FRAME |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_ALTERNATING_MUZZLE,
      0, 1, 1, 1,
      BLOCK_COMMON | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_STAGED_FIRE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_EXTERNAL_CLIENT_STATE),
    S(WORR_LOCAL_ACTION_CATALOG_BFG10K,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_WINDUP_COMMIT, EM_PROJECTILE,
      DEP_AMMO | DEP_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_DEP_LAG_COMPENSATION |
          WORR_LOCAL_ACTION_WEAPON_DEP_RANDOM_STREAM |
          WORR_LOCAL_ACTION_WEAPON_DEP_RULESET |
          WORR_LOCAL_ACTION_WEAPON_DEP_GAME_MODE |
          WORR_LOCAL_ACTION_WEAPON_DEP_CLIENT_FRAME_STATE,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CALLBACK_CAN_ABORT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_CONDITIONAL_AMMO_DEBIT |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_MULTI_FIRE_FRAME |
          WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_PRESENTATION_WINDUP,
      0, 50, 0, 1,
      BLOCK_COMMON | BLOCK_PROJECTILE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_VARIABLE_AMMO_OR_EMISSION |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_STAGED_FIRE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RULESET_BRANCH |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_EXTERNAL_CLIENT_STATE |
          WORR_LOCAL_ACTION_WEAPON_V2_BLOCK_RANDOM_STREAM),
    S(WORR_LOCAL_ACTION_CATALOG_DISRUPTOR,
      WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS,
      WORR_LOCAL_ACTION_WEAPON_EMISSION_TARGETED_PROJECTILE,
      DEP_AMMO | DEP_PROJECTILE | DEP_HISTORICAL |
          WORR_LOCAL_ACTION_WEAPON_DEP_GAME_MODE |
          WORR_LOCAL_ACTION_WEAPON_DEP_CVAR_POLICY,
      WORR_LOCAL_ACTION_WEAPON_BEHAVIOR_WORLD_TARGET_SELECTION, 1, 1, 1, 1,
      BLOCK_COMMON | BLOCK_PROJECTILE | BLOCK_HISTORICAL),
};

#undef S
#undef BLOCK_REPEAT
#undef BLOCK_HISTORICAL
#undef BLOCK_PROJECTILE
#undef BLOCK_COMMON
#undef DEP_HISTORICAL
#undef DEP_AMMO
#undef DEP_PROJECTILE
#undef EM_DEPLOYABLE
#undef EM_BALLISTIC
#undef EM_PROJECTILE

_Static_assert(sizeof(semantics) / sizeof(semantics[0]) ==
                   WORR_LOCAL_ACTION_CATALOG_COUNT,
               "complete local-action weapon semantics catalog required");

static bool output_is_zero(const void *output, size_t size) {
  const uint8_t *bytes = (const uint8_t *)output;
  size_t index;

  if (!output)
    return false;
  for (index = 0; index != size; ++index) {
    if (bytes[index] != 0)
      return false;
  }
  return true;
}

bool Worr_LocalActionWeaponSemanticsValidateV1(
    const worr_local_action_weapon_semantics_v1 *value) {
  const worr_local_action_weapon_semantics_v1 *expected;
  worr_local_action_catalog_entry_v1 catalog_entry;
  worr_local_action_weapon_profile_v1 profile;
  const uint32_t known_emissions =
      WORR_LOCAL_ACTION_WEAPON_EMISSION_MELEE_TRACE |
      WORR_LOCAL_ACTION_WEAPON_EMISSION_HITSCAN |
      WORR_LOCAL_ACTION_WEAPON_EMISSION_STRAIGHT_PROJECTILE |
      WORR_LOCAL_ACTION_WEAPON_EMISSION_BALLISTIC_PROJECTILE |
      WORR_LOCAL_ACTION_WEAPON_EMISSION_DEPLOYABLE |
      WORR_LOCAL_ACTION_WEAPON_EMISSION_CONTINUOUS_BEAM |
      WORR_LOCAL_ACTION_WEAPON_EMISSION_PIERCING_BEAM |
      WORR_LOCAL_ACTION_WEAPON_EMISSION_TARGETED_PROJECTILE |
      WORR_LOCAL_ACTION_WEAPON_EMISSION_AREA_DISCHARGE;
  const uint32_t known_dependencies = UINT32_C(0xffff);
  const uint32_t known_behaviors = UINT32_C(0xffff);
  const uint32_t known_blockers = UINT32_C(0x3fff);
  uint32_t expected_driver;

  if (!value || value->struct_size != sizeof(*value) ||
      value->schema_version != WORR_LOCAL_ACTION_WEAPON_SEMANTICS_ABI_VERSION ||
      value->model_revision !=
          WORR_LOCAL_ACTION_WEAPON_SEMANTICS_MODEL_REVISION ||
      !Worr_LocalActionCatalogIdValidV1(value->catalog_id) ||
      value->trigger_model < WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS ||
      value->trigger_model > WORR_LOCAL_ACTION_WEAPON_TRIGGER_WINDUP_COMMIT ||
      value->emission_flags == 0 ||
      (value->emission_flags & ~known_emissions) != 0 ||
      (value->dependency_flags & ~known_dependencies) != 0 ||
      (value->behavior_flags & ~known_behaviors) != 0 ||
      value->nominal_ammo_debit_min > value->nominal_ammo_debit_max ||
      value->emission_count_min > value->emission_count_max ||
      value->emission_count_max == 0 || value->v2_blockers == 0 ||
      (value->v2_blockers & ~known_blockers) != 0 ||
      value->required_catalog_revision !=
          WORR_LOCAL_ACTION_CATALOG_MODEL_REVISION ||
      value->required_profile_revision !=
          WORR_LOCAL_ACTION_WEAPON_PROFILE_MODEL_REVISION ||
      value->reserved0 != 0) {
    return false;
  }

  switch (value->trigger_model) {
  case WORR_LOCAL_ACTION_WEAPON_TRIGGER_SINGLE_PRESS:
  case WORR_LOCAL_ACTION_WEAPON_TRIGGER_STAGED_MULTI_FRAME:
  case WORR_LOCAL_ACTION_WEAPON_TRIGGER_WINDUP_COMMIT:
    expected_driver = WORR_LOCAL_ACTION_CATALOG_DRIVER_GENERIC;
    break;
  case WORR_LOCAL_ACTION_WEAPON_TRIGGER_HELD_REPEAT:
  case WORR_LOCAL_ACTION_WEAPON_TRIGGER_SPIN_REPEAT:
    expected_driver = WORR_LOCAL_ACTION_CATALOG_DRIVER_REPEATING;
    break;
  case WORR_LOCAL_ACTION_WEAPON_TRIGGER_THROW_HOLD_RELEASE:
    expected_driver = WORR_LOCAL_ACTION_CATALOG_DRIVER_THROW;
    break;
  default:
    return false;
  }

  memset(&catalog_entry, 0, sizeof(catalog_entry));
  memset(&profile, 0, sizeof(profile));
  if (!Worr_LocalActionCatalogCopyEntryV1(value->catalog_id, &catalog_entry) ||
      !Worr_LocalActionWeaponProfileCopyV1(value->catalog_id, &profile) ||
      catalog_entry.legacy_driver != expected_driver ||
      profile.legacy_driver != expected_driver) {
    return false;
  }
  if (catalog_entry.inventory_contract ==
          WORR_LOCAL_ACTION_CATALOG_INVENTORY_NO_AMMO &&
      value->nominal_ammo_debit_max != 0) {
    return false;
  }
  if (catalog_entry.inventory_contract !=
          WORR_LOCAL_ACTION_CATALOG_INVENTORY_NO_AMMO &&
      value->nominal_ammo_debit_max == 0) {
    return false;
  }

  expected = &semantics[value->catalog_id - 1];
  return memcmp(value, expected, sizeof(*value)) == 0;
}

bool Worr_LocalActionWeaponSemanticsCopyV1(
    uint32_t catalog_id, worr_local_action_weapon_semantics_v1 *semantics_out) {
  const worr_local_action_weapon_semantics_v1 *value;

  if (!output_is_zero(semantics_out, sizeof(*semantics_out)) ||
      !Worr_LocalActionCatalogIdValidV1(catalog_id)) {
    return false;
  }
  value = &semantics[catalog_id - 1];
  if (value->catalog_id != catalog_id ||
      !Worr_LocalActionWeaponSemanticsValidateV1(value)) {
    return false;
  }
  *semantics_out = *value;
  return true;
}

static uint64_t hash_u32(uint64_t hash, uint32_t value) {
  unsigned int index;
  for (index = 0; index != 4; ++index) {
    hash ^= (uint8_t)(value & UINT32_C(0xff));
    hash *= UINT64_C(1099511628211);
    value >>= 8;
  }
  return hash;
}

bool Worr_LocalActionWeaponSemanticsDigestV1(uint64_t *digest_out) {
  uint64_t digest = UINT64_C(1469598103934665603);
  uint32_t catalog_id;

  if (!digest_out || *digest_out != 0)
    return false;
  digest = hash_u32(digest, UINT32_C(0x4c415331)); /* LAS1 */
  digest = hash_u32(digest, WORR_LOCAL_ACTION_WEAPON_SEMANTICS_ABI_VERSION);
  digest = hash_u32(digest, WORR_LOCAL_ACTION_WEAPON_SEMANTICS_MODEL_REVISION);
  digest = hash_u32(digest, WORR_LOCAL_ACTION_CATALOG_COUNT);
  for (catalog_id = 1; catalog_id <= WORR_LOCAL_ACTION_CATALOG_COUNT;
       ++catalog_id) {
    const uint8_t *bytes = (const uint8_t *)&semantics[catalog_id - 1];
    size_t index;
    if (!Worr_LocalActionWeaponSemanticsValidateV1(
            &semantics[catalog_id - 1])) {
      return false;
    }
    for (index = 3; index < sizeof(semantics[0]) / sizeof(uint32_t); ++index) {
      uint32_t word;
      memcpy(&word, bytes + index * sizeof(word), sizeof(word));
      digest = hash_u32(digest, word);
    }
  }
  *digest_out = digest;
  return true;
}

bool Worr_LocalActionWeaponSemanticsAuditV2V1(
    const worr_local_action_weapon_semantics_v1 *value,
    uint32_t *blockers_out) {
  if (!blockers_out || *blockers_out != 0 ||
      !Worr_LocalActionWeaponSemanticsValidateV1(value)) {
    return false;
  }
  *blockers_out = value->v2_blockers;
  return true;
}
