// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.

#pragma once

#include "botlib_adapter.hpp"

struct gentity_t;

struct BotNavRecoveryMove {
	int sideSign = 0;
	int framesRemaining = 0;
	bool wait = false;
	bool use = false;
	int interactionAction = 0;
	int interactionEntity = -1;
};

struct BotNavRouteRequest {
	bool hasPositionGoal = false;
	float positionGoal[3] = {};
	bool hasTravelTypeGoal = false;
	int travelTypeGoal = 0;
};

struct BotNavRouteStatus {
	int requests = 0;
	int queries = 0;
	int refreshes = 0;
	int reuses = 0;
	int failures = 0;
	int invalidSlots = 0;
	int cadenceRefreshes = 0;
	int targetRefreshes = 0;
	int driftRefreshes = 0;
	int preferredGoalRefreshes = 0;
	int stuckChecks = 0;
	int stuckStalls = 0;
	int stuckDetections = 0;
	int stuckRepathRefreshes = 0;
	int stuckRecoveryActivations = 0;
	int stuckRecoveryFrames = 0;
	int persistentGoalRequests = 0;
	int persistentGoalAssignments = 0;
	int persistentGoalCacheReuses = 0;
	int persistentGoalClears = 0;
	int persistentGoalFallbacks = 0;
	int failedGoalEvents = 0;
	int itemGoalScans = 0;
	int itemGoalCandidates = 0;
	int itemGoalAssignments = 0;
	int itemGoalReuses = 0;
	int itemGoalClears = 0;
	int itemGoalReservationSkips = 0;
	int itemGoalActiveReservations = 0;
	int itemGoalPeakActiveReservations = 0;
	int itemGoalBlacklistActivations = 0;
	int itemGoalBlacklistSkips = 0;
	int itemGoalBlacklistActive = 0;
	int positionGoalRequests = 0;
	int positionGoalResolved = 0;
	int positionGoalAssignments = 0;
	int positionGoalCacheReuses = 0;
	int positionGoalClears = 0;
	int travelTypeGoalRequests = 0;
	int travelTypeGoalResolved = 0;
	int travelTypeGoalAssignments = 0;
	int travelTypeGoalCacheReuses = 0;
	int travelTypeGoalClears = 0;
	int travelTypeGoalSupportChecks = 0;
	int travelTypeGoalSupported = 0;
	int travelTypeGoalUnsupported = 0;
	int naturalMovementSupportAasLoaded = 0;
	int naturalMovementSupportChecks = 0;
	int naturalMovementSupported = 0;
	int naturalMovementUnsupported = 0;
	int naturalMovementUnsupportedMask = 0;
	int naturalMovementCrouchSupported = 0;
	int naturalMovementCrouchUnsupported = 0;
	int naturalMovementCrouchReason = 0;
	int naturalMovementCrouchArea = 0;
	int naturalMovementCrouchGoalArea = 0;
	int naturalMovementCrouchOriginX = 0;
	int naturalMovementCrouchOriginY = 0;
	int naturalMovementCrouchOriginZ = 0;
	int naturalMovementSwimSupported = 0;
	int naturalMovementSwimUnsupported = 0;
	int naturalMovementSwimReason = 0;
	int naturalMovementSwimArea = 0;
	int naturalMovementSwimGoalArea = 0;
	int naturalMovementSwimOriginX = 0;
	int naturalMovementSwimOriginY = 0;
	int naturalMovementSwimOriginZ = 0;
	int naturalMovementWaterJumpSupported = 0;
	int naturalMovementWaterJumpUnsupported = 0;
	int naturalMovementWaterJumpReason = 0;
	int naturalMovementWaterJumpArea = 0;
	int naturalMovementWaterJumpGoalArea = 0;
	int naturalMovementWaterJumpOriginX = 0;
	int naturalMovementWaterJumpOriginY = 0;
	int naturalMovementWaterJumpOriginZ = 0;
	int interactionChecks = 0;
	int interactionCandidates = 0;
	int interactionActivations = 0;
	int interactionStuckActivations = 0;
	int interactionElevatorActivations = 0;
	int interactionWaitFrames = 0;
	int interactionUseFrames = 0;
	int interactionMisses = 0;
	int interactionWorldEntities = 0;
	int interactionWorldDoors = 0;
	int interactionWorldButtons = 0;
	int interactionWorldPlatforms = 0;
	int interactionWorldTrains = 0;
	int interactionWorldWaters = 0;
	int interactionWorldTriggers = 0;
	int interactionWorldMovers = 0;
	int interactionWorldUseEntities = 0;
	int interactionWorldTouchEntities = 0;
	int debugOverlayFrames = 0;
	int debugOverlayRoutes = 0;
	int debugOverlayGoals = 0;
	int debugOverlayMissingFrames = 0;
	int debugOverlayLines = 0;
	int debugOverlayCrosses = 0;
	int debugOverlayArrows = 0;
	int debugOverlayLabels = 0;
	int debugOverlayPolylinePoints = 0;
	int debugOverlayPolylineSegments = 0;
	int debugOverlayFilteredSlots = 0;
	int debugOverlayFilterMissFrames = 0;
	int lastClient = -1;
	int lastDebugClient = -1;
	int lastDebugFilterClient = -1;
	int lastPersistentGoalArea = 0;
	int lastItemGoalEntity = -1;
	int lastItemGoalArea = 0;
	int lastItemGoalItem = 0;
	int lastItemGoalScore = 0;
	int lastItemGoalReservedEntity = -1;
	int lastItemGoalReservedByClient = -1;
	int lastItemGoalBlacklistedEntity = -1;
	int lastItemGoalBlacklistedByClient = -1;
	int lastItemGoalBlacklistFramesRemaining = 0;
	int lastPositionGoalArea = 0;
	int lastPositionGoalX = 0;
	int lastPositionGoalY = 0;
	int lastPositionGoalZ = 0;
	int lastTravelTypeGoalType = 0;
	int lastTravelTypeGoalArea = 0;
	int lastTravelTypeGoalSupportType = 0;
	int lastTravelTypeGoalSupportArea = 0;
	int lastTravelTypeGoalSupportGoalArea = 0;
	int lastInteractionAction = 0;
	int lastInteractionKind = 0;
	int lastInteractionEntity = -1;
	int lastInteractionSpawnCount = 0;
	int lastInteractionDistanceSq = 0;
	int lastInteractionTravelType = 0;
	int lastInteractionMoveState = 0;
	int lastInteractionFramesRemaining = 0;
	int lastInteractionOriginX = 0;
	int lastInteractionOriginY = 0;
	int lastInteractionOriginZ = 0;
	int lastInteractionBoundsMinX = 0;
	int lastInteractionBoundsMinY = 0;
	int lastInteractionBoundsMinZ = 0;
	int lastInteractionBoundsMaxX = 0;
	int lastInteractionBoundsMaxY = 0;
	int lastInteractionBoundsMaxZ = 0;
	int lastInteractionUse = 0;
	int lastInteractionTouch = 0;
	int lastInteractionSolid = 0;
	int lastInteractionMoveType = 0;
	int lastGoalClearReason = 0;
	int lastFailedGoalReason = 0;
	int lastFailedGoalClient = -1;
	int lastFailedGoalArea = 0;
	int lastFailedGoalEntity = -1;
	int lastFailedGoalItem = 0;
	int lastStuckReason = 0;
	int lastStuckClient = -1;
	int lastStuckFrames = 0;
	int lastStuckDistanceSq = 0;
	int lastStuckProgressDelta = 0;
	int lastStuckRecoveryClient = -1;
	int lastStuckRecoverySide = 0;
	int lastStuckRecoveryFramesRemaining = 0;
	int lastCurrentArea = 0;
	int lastStartArea = 0;
	int lastGoalArea = 0;
	int lastRouteEndArea = 0;
	int lastRoutePointCount = 0;
	int lastTravelTime = 0;
	int lastReachability = 0;
	int lastReachabilityTravelType = 0;
	int lastReachabilityTravelFlags = 0;
	int lastReachabilityEndArea = 0;
	int lastStopEvent = 0;
};

void BotNav_ResetAll();
void BotNav_ResetClient(int clientIndex);
bool BotNav_GetRouteSteer(const gentity_t *bot, const BotNavRouteRequest *request, BotLibAdapterRouteSteer *route);
bool BotNav_GetRecoveryMove(const gentity_t *bot, BotNavRecoveryMove *move);
bool BotNav_DrawDebugOverlay(bool drawRoute, bool drawGoal, int debugClientIndex);
const BotNavRouteStatus &BotNav_GetRouteStatus();
