// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.

#pragma once

struct gentity_t;
struct usercmd_t;

struct BotBrainBlackboardSnapshot {
	bool valid = false;
	int clientIndex = -1;
	int currentEnemyEntity = -1;
	int currentEnemyClient = -1;
	int currentEnemySpawnCount = 0;
	bool currentEnemyVisible = false;
	bool currentEnemyShootable = false;
	int currentEnemyDistanceSquared = 0;
	int currentEnemyHealth = 0;
	int currentEnemyArmor = 0;
	bool currentEnemyEstimateKnown = false;
	int currentEnemyHealthEstimate = 0;
	int currentEnemyArmorEstimate = 0;
	int currentEnemyEffectiveHealthEstimate = 0;
	int currentEnemyEstimateLastObservedTimeMilliseconds = 0;
	int currentEnemyEstimateLastDamageSequence = 0;
	int currentEnemyLastSeenFrame = 0;
	int currentEnemyLastSeenTimeMilliseconds = 0;
	bool currentEnemyRetainedFromMemory = false;
	int currentEnemyMemoryAgeMilliseconds = 0;
	int currentEnemyMemoryWindowMilliseconds = 0;
	int lastSeenEnemyEntity = -1;
	int lastSeenEnemyClient = -1;
	int lastSeenEnemySpawnCount = 0;
	int lastSeenEnemyDistanceSquared = 0;
	int lastSeenFrame = 0;
	int lastSeenTimeMilliseconds = 0;
	int lastSeenOriginX = 0;
	int lastSeenOriginY = 0;
	int lastSeenOriginZ = 0;
	int lastHeardEntity = -1;
	int lastHeardClient = -1;
	int lastHeardFrame = 0;
	int lastHeardTimeMilliseconds = 0;
	int lastHeardOriginX = 0;
	int lastHeardOriginY = 0;
	int lastHeardOriginZ = 0;
	int lastDamagedByEntity = -1;
	int lastDamagedByClient = -1;
	int lastDamagedFrame = 0;
	int lastDamagedTimeMilliseconds = 0;
	int lastDamageOriginX = 0;
	int lastDamageOriginY = 0;
	int lastDamageOriginZ = 0;
	int currentGoalType = 0;
	int currentGoalArea = 0;
	int currentGoalEntity = -1;
	int currentGoalSpawnCount = 0;
	int currentGoalItem = 0;
	int currentGoalPositionX = 0;
	int currentGoalPositionY = 0;
	int currentGoalPositionZ = 0;
	int currentGoalTravelType = 0;
	bool routeStateValid = false;
	int routeStartArea = 0;
	int routeGoalArea = 0;
	int routeEndArea = 0;
	int routePointCount = 0;
	int routeTravelTime = 0;
	int routeReachability = 0;
	int routeReachabilityTravelType = 0;
	int routeReachabilityTravelFlags = 0;
	int routeReachabilityEndArea = 0;
	int routeStopEvent = 0;
	int stuckReason = 0;
	int stuckFrames = 0;
	int stuckDistanceSquared = 0;
	int stuckProgressDelta = 0;
	int stuckRecoverySide = 0;
	int stuckRecoveryFramesRemaining = 0;
	int itemReservationActive = 0;
	int itemReservationEntity = -1;
	int itemReservationOwnerClient = -1;
	int itemReservationItem = 0;
	int itemReservationArea = 0;
	int teamRole = 0;
	int teamRoleObjectiveType = 0;
	int teamRoleTeam = 0;
	int teamRoleTargetTeam = 0;
	int teamRolePriority = 0;
	int teamRoleTargetEntity = -1;
	int teamRoleTargetItem = 0;
	int teamRoleTargetArea = 0;
};

void BotBrain_BeginFrame( gentity_t * bot );
void BotBrain_EndFrame( gentity_t * bot );
bool BotBrain_BuildFrameCommand( gentity_t * bot, usercmd_t * cmd );
void BotBrain_ResetChatPolicyState();
void BotBrain_PrintFrameCommandStatus( int expectedMinFrames, int expectedMinCommands );
bool BotBrain_GetBlackboardSnapshot( int clientIndex, BotBrainBlackboardSnapshot * snapshot );
