//===========================================================================
//
// Name:			chars.h
// Function:		bot characteristics used by WORR Q3-style botfiles
// Source:			WORR original compatibility table
// Tab Size:		4 (real tabs)
//===========================================================================

// Values follow the Quake III Arena characteristic order for the shared
// BotLib vocabulary. WORR extension keys stay in a high range so future native
// character parsers can keep them distinct from idTech3-era fields.

#define CHARACTERISTIC_NAME							0
#define CHARACTERISTIC_GENDER						1
#define CHARACTERISTIC_ATTACK_SKILL					2
#define CHARACTERISTIC_WEAPONWEIGHTS				3
#define CHARACTERISTIC_VIEW_FACTOR					4
#define CHARACTERISTIC_VIEW_MAXCHANGE				5
#define CHARACTERISTIC_REACTIONTIME					6
#define CHARACTERISTIC_AIM_ACCURACY					7
#define CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		8
#define CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			9
#define CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	10
#define CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	11
#define CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		12
#define CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		13
#define CHARACTERISTIC_AIM_ACCURACY_RAILGUN			14
#define CHARACTERISTIC_AIM_ACCURACY_BFG10K			15
#define CHARACTERISTIC_AIM_SKILL					16
#define CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		17
#define CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	18
#define CHARACTERISTIC_AIM_SKILL_PLASMAGUN			19
#define CHARACTERISTIC_AIM_SKILL_BFG10K				20

#define CHARACTERISTIC_CHAT_FILE					21
#define CHARACTERISTIC_CHAT_NAME					22
#define CHARACTERISTIC_CHAT_CPM						23
#define CHARACTERISTIC_CHAT_INSULT					24
#define CHARACTERISTIC_CHAT_MISC					25
#define CHARACTERISTIC_CHAT_STARTENDLEVEL			26
#define CHARACTERISTIC_CHAT_ENTEREXITGAME			27
#define CHARACTERISTIC_CHAT_KILL					28
#define CHARACTERISTIC_CHAT_DEATH					29
#define CHARACTERISTIC_CHAT_ENEMYSUICIDE			30
#define CHARACTERISTIC_CHAT_HITTALKING				31
#define CHARACTERISTIC_CHAT_HITNODEATH				32
#define CHARACTERISTIC_CHAT_HITNOKILL				33
#define CHARACTERISTIC_CHAT_RANDOM					34
#define CHARACTERISTIC_CHAT_REPLY					35

#define CHARACTERISTIC_CROUCHER						36
#define CHARACTERISTIC_JUMPER						37
#define CHARACTERISTIC_WEAPONJUMPING				38
#define CHARACTERISTIC_GRAPPLE_USER					39
#define CHARACTERISTIC_ITEMWEIGHTS					40
#define CHARACTERISTIC_AGGRESSION					41
#define CHARACTERISTIC_SELFPRESERVATION				42
#define CHARACTERISTIC_VENGEFULNESS					43
#define CHARACTERISTIC_CAMPER						44
#define CHARACTERISTIC_EASY_FRAGGER					45
#define CHARACTERISTIC_ALERTNESS					46
#define CHARACTERISTIC_FIRETHROTTLE					47
#define CHARACTERISTIC_WALKER						48

#define WORR_SKIN									1000
#define WORR_TEAM									1001
#define WORR_AIM_ERROR								1002
#define WORR_PREFERRED_WEAPON						1003
#define WORR_CHAT_PERSONALITY						1004
#define WORR_ROLE									1005
#define WORR_MOVEMENT_STYLE							1006
#define WORR_REACTION_JITTER_MS						1007
#define WORR_AIM_TRACKING_NOISE						1008
#define WORR_AIM_LEAD_SCALE							1009
#define WORR_COMBAT_FOV								1010
#define WORR_TEAMPLAY_BIAS							1011
#define WORR_OBJECTIVE_BIAS							1012
#define WORR_FRIENDLY_FIRE_CARE						1013
#define WORR_ITEM_GREED								1014
#define WORR_ITEM_DENIAL							1015
#define WORR_POWERUP_TIMING							1016
#define WORR_RETREAT_HEALTH							1017
