#!/usr/bin/env python3
"""Regenerate src/rend_vk/vk_world_spv.h from the GLSL sources.

The native Vulkan renderer embeds its world/shadow shaders as SPIR-V arrays.
The GLSL sources of truth live in src/rend_vk/shaders/. Whenever they change,
run this script so the embedded header, the C-side UBO struct
(vk_shadow_uniform_t), and the descriptor-set layout in vk_shadow.c stay in
sync. The ShadowPages uniform block layout and the set=2 bindings in
vk_world_shadow.frag MUST match vk_shadow.c exactly; a mismatch silently
corrupts every shadow page matrix at runtime.

Usage:
    python tools/gen_vk_world_spv.py [--validate]
"""

from __future__ import annotations

import argparse
import glob
import os
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SHADER_DIR = REPO_ROOT / "src" / "rend_vk" / "shaders"
OUTPUT_HEADER = REPO_ROOT / "src" / "rend_vk" / "vk_world_spv.h"

# (source file, C array symbol)
SHADERS = (
    ("vk_world_shadow.vert", "vk_world_vert_spv"),
    ("vk_world_shadow.frag", "vk_world_frag_spv"),
    ("vk_shadow_moment.frag", "vk_shadow_moment_frag_spv"),
)

WORDS_PER_LINE = 8


def find_sdk_tool(name: str) -> str:
    candidates = []
    sdk = os.environ.get("VULKAN_SDK")
    if sdk:
        candidates.append(Path(sdk) / "Bin" / f"{name}.exe")
        candidates.append(Path(sdk) / "bin" / name)
    candidates.extend(
        Path(p) / f"{name}.exe"
        for p in sorted(glob.glob(r"C:\VulkanSDK\*\Bin"), reverse=True)
    )
    for candidate in candidates:
        if candidate.is_file():
            return str(candidate)
    # Fall back to PATH.
    return name


def compile_shader(compiler: str, source: Path) -> bytes:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / (source.name + ".spv")
        cmd = [compiler, "-V", str(source), "-o", str(out)]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            sys.stderr.write(result.stdout)
            sys.stderr.write(result.stderr)
            raise SystemExit(f"glslangValidator failed for {source.name}")
        return out.read_bytes()


def validate_spirv(validator: str, blob: bytes, name: str) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / f"{name}.spv"
        path.write_bytes(blob)
        result = subprocess.run([validator, str(path)],
                                capture_output=True, text=True)
        if result.returncode != 0:
            sys.stderr.write(result.stdout)
            sys.stderr.write(result.stderr)
            raise SystemExit(f"spirv-val failed for {name}")


def format_array(symbol: str, blob: bytes) -> str:
    if len(blob) % 4 != 0:
        raise SystemExit(f"{symbol}: SPIR-V size {len(blob)} not word aligned")
    words = struct.unpack(f"<{len(blob) // 4}I", blob)
    lines = [f"static const uint32_t {symbol}[] = {{"]
    for i in range(0, len(words), WORDS_PER_LINE):
        chunk = ", ".join(f"0x{w:08x}u" for w in words[i:i + WORDS_PER_LINE])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"static const size_t {symbol}_size = sizeof({symbol});")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validate", action="store_true",
                        help="run spirv-val on each generated module")
    args = parser.parse_args()

    compiler = find_sdk_tool("glslangValidator")
    validator = find_sdk_tool("spirv-val") if args.validate else None

    sections = []
    for source_name, symbol in SHADERS:
        source = SHADER_DIR / source_name
        if not source.is_file():
            raise SystemExit(f"missing shader source: {source}")
        blob = compile_shader(compiler, source)
        if validator:
            validate_spirv(validator, blob, symbol)
        sections.append(format_array(symbol, blob))
        print(f"{source_name}: {len(blob)} bytes -> {symbol}")

    sources = ", ".join(name for name, _ in SHADERS)
    header = (
        f"/* Auto-generated by tools/gen_vk_world_spv.py from "
        f"src/rend_vk/shaders/{{{sources}}}. Do not edit. */\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        "#include <stddef.h>\n"
        "\n"
        + "\n\n".join(sections)
        + "\n"
    )
    OUTPUT_HEADER.write_text(header, newline="\n")
    print(f"wrote {OUTPUT_HEADER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
