#!/usr/bin/env python3
"""Generate a repeatable multiplayer bot playtest checklist for WORR."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
from dataclasses import dataclass
from typing import Any, Iterable


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = pathlib.Path(".tmp") / "bot_playtest"
SCHEMA = "worr.bot_playtest.v1"
NOTES_SCHEMA = "worr.bot_playtest.notes.v1"

BOT_PROFILES = ("vanguard", "vector", "bulwark", "relay", "smoke")
REQUIRED_MODES = ("FFA", "Duel", "TDM", "CTF")

COMMON_CVARS: tuple[tuple[str, str], ...] = (
    ("deathmatch", "1"),
    ("coop", "0"),
    ("bot_enable", "1"),
    ("bot_behavior_enable", "1"),
    ("bot_min_players", "0"),
    ("bot_profile", ""),
    ("bot_skill", "3"),
    ("bot_allow_item_timers", "1"),
    ("bot_item_timer_fuzz_ms", "0"),
    ("bot_allow_rocketjump", "0"),
    ("bot_allow_chat", "0"),
)

MODE_POLICY_CVARS: tuple[str, ...] = (
    "bot_ffa_roam_route",
    "bot_ffa_spawn_camp_avoidance",
    "bot_ffa_spawn_camp_combat_avoidance",
    "bot_ffa_item_roles",
    "bot_ffa_role_combat",
    "bot_duel_live_pacing",
    "bot_team_role_route",
    "bot_team_item_roles",
    "bot_team_resource_denial",
    "bot_team_fire_avoidance",
    "bot_team_role_combat",
    "bot_ctf_role_route",
    "bot_ctf_role_combat",
    "bot_ctf_objective_route",
    "bot_ctf_objective_transitions",
    "bot_ctf_item_roles",
)

FORBIDDEN_PUBLIC_TOKENS = (
    "sv_bot_",
    "sg_bot_",
    "smoke_bot_",
    "smoke_",
    "_smoke",
)


@dataclass(frozen=True)
class PlaytestCase:
    case_id: str
    title: str
    mode: str
    map_name: str
    bot_target: int
    duration_minutes: int
    cvars: tuple[tuple[str, str], ...]
    profiles: tuple[str, ...]
    focus: tuple[str, ...]
    observations: tuple[str, ...]
    pass_criteria: tuple[str, ...]
    failure_signals: tuple[str, ...]

    @property
    def config_name(self) -> str:
        return f"bot_playtest_{self.case_id}.cfg"

    def all_cvars(self) -> tuple[tuple[str, str], ...]:
        reset_cvars = tuple((name, "0") for name in MODE_POLICY_CVARS)
        return (*COMMON_CVARS, *reset_cvars, *self.cvars)

    def command_lines(self) -> tuple[str, ...]:
        return (
            *(f"set {name} {config_value(value)}" for name, value in self.all_cvars()),
            f"map {self.map_name}",
            "botlist",
        )

    def config_text(self) -> str:
        lines = [
            f"// Generated by tools/bot_playtest/generate_bot_playtest.py",
            f"// Case: {self.case_id} ({self.mode})",
            f"// Goal: {self.title}",
            "kickbots",
            *self.command_lines(),
            "",
            "// After bots spawn, run: botlist",
            "// Watch for the failure signals listed in the generated checklist.",
        ]
        return "\n".join(lines) + "\n"

    def to_json(self) -> dict[str, Any]:
        return {
            "id": self.case_id,
            "title": self.title,
            "mode": self.mode,
            "map": self.map_name,
            "bot_target": self.bot_target,
            "duration_minutes": self.duration_minutes,
            "config": self.config_name,
            "profiles": list(self.profiles),
            "cvars": [{"name": name, "value": value} for name, value in self.all_cvars()],
            "commands": list(self.command_lines()),
            "focus": list(self.focus),
            "observations": list(self.observations),
            "pass_criteria": list(self.pass_criteria),
            "failure_signals": list(self.failure_signals),
        }


def config_value(value: str) -> str:
    if value == "":
        return '""'
    if any(ch.isspace() for ch in value):
        escaped = value.replace('"', r'\"')
        return f'"{escaped}"'
    return value


def default_playtest_cases() -> tuple[PlaytestCase, ...]:
    return (
        PlaytestCase(
            case_id="ffa_practice",
            title="FFA roam, item pickup, close-threat spacing, and weak-state retreat",
            mode="FFA",
            map_name="q2dm1",
            bot_target=4,
            duration_minutes=8,
            profiles=BOT_PROFILES,
            cvars=(
                ("maxclients", "8"),
                ("maxplayers", "8"),
                ("timelimit", "10"),
                ("fraglimit", "30"),
                ("g_gametype", "1"),
                ("bot_min_players", "4"),
                ("bot_ffa_roam_route", "1"),
                ("bot_ffa_spawn_camp_avoidance", "1"),
                ("bot_ffa_item_roles", "1"),
                ("bot_ffa_role_combat", "1"),
                ("bot_ffa_spawn_camp_combat_avoidance", "1"),
            ),
            focus=(
                "Bots should leave spawn pressure and commit to item routes when no target is visible.",
                "Bots should not walk directly into a nearby target until the models overlap.",
                "Weak bots should break contact for health, armor, or a safer weapon instead of blaster-chasing stacked players.",
            ),
            observations=(
                "Use botlist after the match starts and confirm the population reaches four through bot_min_players.",
                "Spectate each profile once: vanguard, vector, bulwark, relay, and smoke should rotate into auto-fill slots over repeated runs.",
                "Watch one minute with no human attacks; at least two bots should roam toward items instead of spinning in place.",
            ),
            pass_criteria=(
                "At least three distinct item areas are visited during the run.",
                "Close-range fights show strafing, backing off, or re-targeting instead of sustained model overlap.",
                "A low-health bot seeks recovery or disengages at least once when a stronger enemy is nearby.",
            ),
            failure_signals=(
                "A bot spins in one spot for more than five seconds with no visible target.",
                "Multiple bots stay pressed against the same wall or corner after route goals are available.",
                "A bot repeatedly charges a stacked enemy with only the blaster and no retreat attempt.",
            ),
        ),
        PlaytestCase(
            case_id="duel_rotation",
            title="Duel live pacing, item denial, spawn pressure, and queue boundaries",
            mode="Duel",
            map_name="q2dm1",
            bot_target=2,
            duration_minutes=8,
            profiles=("vanguard", "vector", "bulwark"),
            cvars=(
                ("maxclients", "4"),
                ("maxplayers", "2"),
                ("g_allow_duel_queue", "1"),
                ("timelimit", "10"),
                ("fraglimit", "15"),
                ("g_gametype", "2"),
                ("bot_min_players", "2"),
                ("bot_duel_live_pacing", "1"),
            ),
            focus=(
                "Only two active players should be in the Duel arena while surplus clients remain outside active play.",
                "The leading bot should deny major items instead of chasing every visible target.",
                "The trailing or weak bot should prefer recovery, weapon pickup, or spawn escape before re-engaging.",
            ),
            observations=(
                "Run botlist after the first spawn wave and verify two active bot slots satisfy bot_min_players.",
                "Join as a human and confirm the auto-filled population trims or queues without exceeding the intended active Duel count.",
                "Watch one post-frag spawn sequence for pressure that does not collapse into wall-sticking.",
            ),
            pass_criteria=(
                "Duel population remains stable at the target active count.",
                "Bots contest or deny at least one major weapon, armor, powerup, or ammo route.",
                "A close spawn encounter resolves into movement or combat instead of both bots standing nose-to-nose.",
            ),
            failure_signals=(
                "bot_min_players remains below two after the map has been running for several seconds.",
                "A bot ignores available weapons or armor while chasing a stronger opponent with the blaster.",
                "Queue or spectator handling allows extra active Duel participants beyond maxplayers.",
            ),
        ),
        PlaytestCase(
            case_id="tdm_roles",
            title="TDM role routes, friendly-fire avoidance, resource denial, and team spacing",
            mode="TDM",
            map_name="q2dm8",
            bot_target=6,
            duration_minutes=10,
            profiles=("vanguard", "vector", "bulwark", "relay", "smoke"),
            cvars=(
                ("maxclients", "8"),
                ("maxplayers", "6"),
                ("timelimit", "12"),
                ("fraglimit", "50"),
                ("g_gametype", "3"),
                ("bot_min_players", "6"),
                ("bot_team_role_route", "1"),
                ("bot_team_item_roles", "1"),
                ("bot_team_resource_denial", "1"),
                ("bot_team_fire_avoidance", "1"),
                ("bot_team_role_combat", "1"),
            ),
            focus=(
                "Teams should spread into role-shaped routes instead of forming one close clump.",
                "Bots should avoid firing through teammates when a friendly line blocks the shot.",
                "Resource-denial bots should contest important pickups without abandoning survival needs.",
            ),
            observations=(
                "Use the scoreboard and botlist to confirm six bot-controlled players enter the match.",
                "Watch a teammate crossing a firing lane; the shooter should pause, strafe, or change target rather than firing through them.",
                "Follow a support or defender profile for a full route cycle and confirm it does not simply shadow an enemy at touching distance.",
            ),
            pass_criteria=(
                "Both teams occupy at least two separate route areas during the run.",
                "At least one contested item is denied, delayed, or collected by the team that is applying pressure.",
                "Friendly-line encounters do not produce obvious sustained teammate shooting.",
            ),
            failure_signals=(
                "All bots collapse into one wall-adjacent pile for more than one fight.",
                "A bot keeps walking forward into a teammate or enemy at point-blank range without a spacing decision.",
                "A low-resource bot refuses nearby health or armor while continuing an unfavorable attack.",
            ),
        ),
        PlaytestCase(
            case_id="ctf_objectives",
            title="CTF objective transitions, carrier support, base return, and item roles",
            mode="CTF",
            map_name="q2ctf1",
            bot_target=6,
            duration_minutes=12,
            profiles=("vanguard", "vector", "bulwark", "relay", "smoke"),
            cvars=(
                ("maxclients", "8"),
                ("maxplayers", "6"),
                ("timelimit", "12"),
                ("capturelimit", "3"),
                ("g_gametype", "5"),
                ("bot_min_players", "6"),
                ("bot_ctf_role_route", "1"),
                ("bot_ctf_role_combat", "1"),
                ("bot_ctf_objective_route", "1"),
                ("bot_ctf_objective_transitions", "1"),
                ("bot_ctf_item_roles", "1"),
            ),
            focus=(
                "Attackers should route to the enemy flag, defenders should recover base position, and support bots should react to carriers.",
                "Dropped and returned flags should change objective ownership without leaving bots spinning.",
                "Bots should collect useful items on the way to an objective instead of ignoring the map economy.",
            ),
            observations=(
                "Confirm six bots enter with a reasonable red/blue split before judging objective behavior.",
                "Force or wait for one flag pickup and one flag drop, then watch the nearby objective-owner response.",
                "Spectate the carrier after pickup and confirm at least one same-team bot reacts by escorting, clearing, or returning home.",
            ),
            pass_criteria=(
                "At least one enemy flag pickup produces an immediate route or combat response.",
                "A dropped flag attracts return/steal pressure instead of being ignored until timeout.",
                "Defenders and support profiles do not all chase the same enemy at touching distance while their flag is threatened.",
            ),
            failure_signals=(
                "Bots spin in place after a flag pickup, drop, or return transition.",
                "All bots abandon both bases to chase a visible player for the full observation window.",
                "A carrier walks into a wall or teammate cluster instead of following a route home.",
            ),
        ),
    )


def validate_cases(cases: Iterable[PlaytestCase]) -> list[str]:
    failures: list[str] = []
    case_list = list(cases)
    modes = {case.mode for case in case_list}
    for mode in REQUIRED_MODES:
        if mode not in modes:
            failures.append(f"missing required playtest mode: {mode}")

    ids: set[str] = set()
    for case in case_list:
        if case.case_id in ids:
            failures.append(f"duplicate playtest case id: {case.case_id}")
        ids.add(case.case_id)
        if case.bot_target <= 0:
            failures.append(f"{case.case_id} must request at least one bot")
        if not case.pass_criteria:
            failures.append(f"{case.case_id} has no pass criteria")
        if not case.failure_signals:
            failures.append(f"{case.case_id} has no failure signals")
        text = case.config_text()
        for token in FORBIDDEN_PUBLIC_TOKENS:
            if token in text:
                failures.append(f"{case.case_id} generated forbidden public token: {token}")
    return failures


def now_utc() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def rel(path: pathlib.Path, repo_root: pathlib.Path) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        return str(path)


def render_markdown(
    cases: Iterable[PlaytestCase],
    *,
    repo_root: pathlib.Path,
    output_dir: pathlib.Path,
    base_game: str,
    install_dir: pathlib.Path,
    generated_at: str,
) -> str:
    case_list = list(cases)
    total_minutes = sum(case.duration_minutes for case in case_list)
    executable = ".\\worr_ded_x86_64.exe"
    install_game_dir = install_dir / base_game
    generated_inside_game_dir = output_dir.resolve() == install_game_dir.resolve()

    lines = [
        "# WORR Bot Multiplayer Playtest Checklist",
        "",
        f"Generated: `{generated_at}`",
        f"Cases: `{len(case_list)}`",
        f"Estimated active time: `{total_minutes} minutes`",
        "",
        "## Before You Start",
        "",
        "- Use a fresh staged build under `.install/` when validating release candidates.",
        "- Generate executable configs into `.install/basew` if you want to run them with `+exec`.",
        "- Keep the console open and use `botlist` after each map starts.",
        "- Treat spinning in place, wall-sticking, point-blank overlap, and blaster-only suicide pushes as failures to investigate.",
        "",
        "## Generate Configs",
        "",
        "```powershell",
        "python tools\\bot_playtest\\generate_bot_playtest.py --output-dir .tmp\\bot_playtest",
        "python tools\\bot_playtest\\generate_bot_playtest.py --output-dir .install\\basew",
        "```",
        "",
    ]

    for index, case in enumerate(case_list, start=1):
        lines.extend(
            [
                f"## {index}. {case.title}",
                "",
                f"- Case: `{case.case_id}`",
                f"- Mode: `{case.mode}`",
                f"- Map: `{case.map_name}`",
                f"- Bot target: `{case.bot_target}`",
                f"- Duration: `{case.duration_minutes} minutes`",
                f"- Profiles: `{', '.join(case.profiles)}`",
                "",
                "Focus:",
            ]
        )
        lines.extend(f"- {item}" for item in case.focus)
        lines.extend(["", "Run:"])
        if generated_inside_game_dir:
            lines.extend(
                [
                    "",
                    "```powershell",
                    f"cd {rel(install_dir, repo_root)}",
                    f"{executable} +set basedir . +set game {base_game} +exec {case.config_name}",
                    "```",
                ]
            )
        else:
            lines.extend(
                [
                    "",
                    "```text",
                    *(case.command_lines()),
                    "```",
                ]
            )
        lines.extend(["", "Observe:"])
        lines.extend(f"- {item}" for item in case.observations)
        lines.extend(["", "Pass criteria:"])
        lines.extend(f"- {item}" for item in case.pass_criteria)
        lines.extend(["", "Failure signals:"])
        lines.extend(f"- {item}" for item in case.failure_signals)
        lines.append("")

    lines.extend(
        [
            "## Wrap-Up",
            "",
            "- Save the generated JSON artifact with the release or bug report notes.",
            "- Record the exact map, profile mix, bot count, and any visible failure signal.",
            "- Re-run `tools/bot_release/run_bot_acceptance.py` after updating bot behavior or staged assets.",
            "",
        ]
    )
    return "\n".join(lines)


def build_payload(
    cases: Iterable[PlaytestCase],
    *,
    repo_root: pathlib.Path,
    output_dir: pathlib.Path,
    base_game: str,
    generated_at: str,
) -> dict[str, Any]:
    case_list = list(cases)
    return {
        "schema": SCHEMA,
        "generated_at": generated_at,
        "repo_root": str(repo_root.resolve()),
        "output_dir": str(output_dir.resolve()),
        "base_game": base_game,
        "summary": {
            "cases": len(case_list),
            "modes": sorted({case.mode for case in case_list}),
            "total_minutes": sum(case.duration_minutes for case in case_list),
            "bot_profiles": list(BOT_PROFILES),
        },
        "cases": [case.to_json() for case in case_list],
    }


def build_notes_template(
    cases: Iterable[PlaytestCase],
    *,
    playtest_artifact: str,
    generated_at: str,
) -> dict[str, Any]:
    return {
        "schema": NOTES_SCHEMA,
        "generated_at": generated_at,
        "playtest_artifact": playtest_artifact,
        "operator": "",
        "build": "",
        "server": "",
        "notes": "",
        "cases": [
            {
                "id": case.case_id,
                "outcome": "pending",
                "duration_minutes": case.duration_minutes,
                "botlist": "",
                "profiles_observed": [],
                "failure_signals": [],
                "custom_failure_signals": [],
                "repro_steps": [],
                "notes": "",
            }
            for case in cases
        ],
    }


def generate_outputs(
    *,
    repo_root: pathlib.Path = REPO_ROOT,
    output_dir: pathlib.Path = DEFAULT_OUTPUT_DIR,
    base_game: str = "basew",
    install_dir: pathlib.Path | None = None,
) -> dict[str, Any]:
    repo_root = repo_root.resolve()
    output_dir = (repo_root / output_dir).resolve() if not output_dir.is_absolute() else output_dir.resolve()
    install_dir = (install_dir or repo_root / ".install").resolve()
    cases = default_playtest_cases()
    failures = validate_cases(cases)
    if failures:
        raise SystemExit("\n".join(failures))

    output_dir.mkdir(parents=True, exist_ok=True)
    generated_at = now_utc()

    config_paths: list[pathlib.Path] = []
    for case in cases:
        path = output_dir / case.config_name
        path.write_text(case.config_text(), encoding="utf-8", newline="\n")
        config_paths.append(path)

    markdown_path = output_dir / "bot_multiplayer_playtest.md"
    json_path = output_dir / "bot_multiplayer_playtest.json"
    notes_template_path = output_dir / "bot_multiplayer_playtest_notes_template.json"
    markdown = render_markdown(
        cases,
        repo_root=repo_root,
        output_dir=output_dir,
        base_game=base_game,
        install_dir=install_dir,
        generated_at=generated_at,
    )
    markdown_path.write_text(markdown, encoding="utf-8", newline="\n")

    payload = build_payload(
        cases,
        repo_root=repo_root,
        output_dir=output_dir,
        base_game=base_game,
        generated_at=generated_at,
    )
    payload["artifacts"] = {
        "markdown": rel(markdown_path, repo_root),
        "json": rel(json_path, repo_root),
        "notes_template": rel(notes_template_path, repo_root),
        "configs": [rel(path, repo_root) for path in config_paths],
    }
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8", newline="\n")

    notes_template = build_notes_template(
        cases,
        playtest_artifact=rel(json_path, repo_root),
        generated_at=generated_at,
    )
    notes_template_path.write_text(
        json.dumps(notes_template, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return payload


def print_summary(payload: dict[str, Any]) -> None:
    summary = payload["summary"]
    print(
        "generated "
        f"{summary['cases']} bot playtest cases for {', '.join(summary['modes'])} "
        f"({summary['total_minutes']} minutes)"
    )
    artifacts = payload["artifacts"]
    print(f"markdown: {artifacts['markdown']}")
    print(f"json: {artifacts['json']}")
    print(f"notes_template: {artifacts['notes_template']}")
    for path in artifacts["configs"]:
        print(f"config: {path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=pathlib.Path,
        default=REPO_ROOT,
        help="repository root; defaults to the script's repository",
    )
    parser.add_argument(
        "--output-dir",
        type=pathlib.Path,
        default=DEFAULT_OUTPUT_DIR,
        help="directory for generated markdown, JSON, and cfg files",
    )
    parser.add_argument(
        "--base-game",
        default="basew",
        help="game directory name used in generated launch examples",
    )
    parser.add_argument(
        "--install-dir",
        type=pathlib.Path,
        default=None,
        help="staged install root used in launch examples; defaults to .install",
    )
    parser.add_argument(
        "--format",
        choices=("text", "json"),
        default="text",
        help="stdout format",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = generate_outputs(
        repo_root=args.repo_root,
        output_dir=args.output_dir,
        base_game=args.base_game,
        install_dir=args.install_dir,
    )
    if args.format == "json":
        print(json.dumps(payload, indent=2))
    else:
        print_summary(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
